#!/bin/bash

set -o pipefail

source /opt/tools/utils

# Plays the popup sound for the incoming notification
# based on the notification's parameters.
# Arguments:
#  appname: the notification caller
#  summary: the summary of the notification
#  body:    the body of the notification
#  icon:    the notification icon
#  urgency: the urgency value
run () {
  local appname="${1}"
  local summary="${2}"
  local body="${3}"
  local urgency="${5}"

  local sound='normal'

  if equals "${urgency}" 'CRITICAL'; then
    sound='critical'
  fi

  LC_ALL=en_US.UTF-8 pw-play --volume=0.5 "/usr/share/sounds/stack/${sound}.wav"
}

run "$@"

