#!/bin/bash

set -o pipefail

SETTINGS_FILE="${HOME}/.config/stack/notifications.json"

# Plays the popup sound for the incoming notification
# based on the notification's parameters.
# Arguments:
#  appname: the notification caller
#  summary: the summary of the notification
#  body:    the body of the notification
#  icon:    the notification icon
#  urgency: the urgency value
play_popup_sound () {
  local appname="${1}"
  local summary="${2}"
  local body="${3}"
  local urgency="${5}"

  local sound='normal'

  if [[ "${urgency}" == "CRITICAL" ]]; then
    sound='critical'
  fi

  local volume=0
  volume="$(jq -cer '.volume' "${SETTINGS_FILE}")"

  if [[ $? -ne 0 ]]; then
    volume=1
  fi

  pw-play --volume="${volume}" "/usr/share/sounds/dunst/${sound}.wav"
}

play_popup_sound "$@"
