#!/usr/bin/env bash

show_apps_menu () {
  rofi -show drun
}

show_windows_menu () {
  rofi -show window
}

show_power_menu () {
  local options=''
  options+='Shutdown\n'
  options+='Reboot\n'
  options+='Suspend\n'
  options+='Lock\n'
  options+='Blank\n'
  options+='Logout'

  local HIDE_PROMT="inputbar {children: [entry];}"
  local EXACT_LINES="listview {lines: 6;}"

  local CHOSEN="$(printf "${options}" | rofi -dmenu -i -theme-str "${HIDE_PROMT} ${EXACT_LINES}")"

  case "$CHOSEN" in
    "Shutdown") power -qs shutdown;;
    "Reboot") power -qs reboot;;
    "Suspend") power -qs suspend;;
    "Lock") security -qs lock screen;;
    "Blank") power -qs blank;;
    "Logout") security -qs logout user;;
    *) exit 1;;
  esac
}

case "$1" in
 "apps") show_apps_menu;;
 "windows") show_windows_menu;;
 "power") show_power_menu;;
 *)
  echo 'Ooops, invalid launch menu!'
  exit 1;;
esac

