#!/usr/bin/env sh

clear

SELECTION=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

printf "(s)election/(c)urrent? [default=c] "
read -r REPLY

if [ "$REPLY" = "s" ]; then
  FILES=$(tr '\0' '\n' < "$SELECTION")

  printf "\nFile(s) to remove:\n"
  printf "%s\n" "$FILES"
  printf "Do you want to proceed? [y/N] "
  read -r CONFIRM

  if [ "$CONFIRM" = "y" ] || [ "$CONFIRM" = "Y" ]; then
    sed 's|'"$PWD/"'||g' < "$SELECTION" | xargs -0 -I {} rm -rf {}
  fi
else
  FILE="$PWD/$1"

  printf "\nFile to remove:\n"
  printf "%s\n" "$FILE"
  printf "Do you want to proceed? [y/N] "
  read -r CONFIRM

  if [ "$CONFIRM" = "y" ] || [ "$CONFIRM" = "Y" ]; then
    rm -rf "$FILE"
  fi
fi

# Clear selection
if [ "$REPLY" = "s" ] && [ -p "$NNN_PIPE" ]; then
  printf "-" > "$NNN_PIPE"
fi
