#!/usr/bin/env bash

shopt -s nocasematch

clear

LOOP="true"

while [[ $LOOP = "true" ]]; do
  clear
  trash-list
  echo ""

  echo -e "Which trash operation to apply?"
  read -rep "(r)estore re(m)ove (e)mpty (q)uit: " REPLY

  while [[ ! $REPLY =~ ^(r|m|e|q)$ ]]; do
    read -rep "Please enter a valid operation: " REPLY
  done

  echo ""

  if [[ $REPLY == "q" ]]; then
    LOOP="false"
  elif [[ $REPLY == "r" ]]; then
    trash-restore
  elif [[ $REPLY == "m" ]]; then
    read -rep "Enter the file(s) to remove (blank to cancel): " FILES

    if [[ ! -z $FILES ]]; then
      read -rep "File(s) will be gone forever, proceed? [y/N] " REPLY
      REPLY=${REPLY:-"no"}

      if [[ $REPLY =~ ^(yes|y)$ ]]; then
        trash-rm $FILES
      fi
    fi
  elif [[ $REPLY == "e" ]]; then
    trash-empty
  fi

  echo ""
done

clear
