#!/bin/sh

feh --no-fehbg --bg-fill ~/images/wallpapers/wallpaper.jpeg &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch &
dunst &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config external_rules_command $HOME/.config/bspwm/rules
