#!/bin/bash

set -o pipefail

source /opt/stack/utils
source /opt/stack/bluetooth/helpers

# Shows the current status of bluetooth service
# and connected devices.
# Arguments:
#  None
# Outputs:
#  A long list of bluetooth data.
show_status () {
  systemctl status --lines 0 --no-pager bluetooth.service | awk '{
    if ($0 ~ / *Active/) {
      l = "Service"
      v = $2" "$3
    } else l = ""

    if (l) printf "%-14s %s\n",l":",v
  }' || return 1

  local query=''
  query+='Controller:    \(.name) [\(.alias)]\n'
  query+='Address:       \(.address)\n'
  query+='Powered:       \(.powered)\n'
  query+='Scanning:      \(.discovering)\n'
  query+='Pairable:      \(.pairable)\n'
  query+='Discoverable:  \(.discoverable)'
  
  find_controller | jq -cer ".[0]|\"${query}\""
  
  if [[ $? -ne 0 ]]; then
    echo "Controller:    none"
  fi

  local query=''
  query+='if .|length > 0 then .[]|.address else "" end'

  local devices=''
  devices="$(find_devices "connected" | jq -cer "${query}")" || return 1

  if [[ -z "${devices}" ]]; then
    return 0
  fi

  local query=''
  query+='Device:        \(.name)\n'
  query+='Address:       \(.address)\n'
  query+='Type:          \(.icon)'
  query="[.[]|\"${query}\"]|join(\"\n\")"

  local device=''
  while read -r device; do
    echo
    find_device "${device}" | jq -cer "${query}" || return 1
  done <<< "${devices}"
}

# Shows the logs of the bluetooth service.
# Arguments:
#  None
# Outputs:
#  A long list of log messages.
show_logs () {
  systemctl status --no-pager bluetooth.service | tail -n +13 || return 1
}

# Shows the list of available controllers.
# Arguments:
#  None
# Outputs:
#  A list of bluetooth controllers.
list_controllers () {
  local controllers=''
  controllers="$(find_controllers)"

  if [[ $? -ne 0 ]]; then
    echo "Unable to read controllers"
    return 2
  fi

  local len=0
  len="$(count "${controllers}")" || return 1

  if [[ ${len} -eq 0 ]]; then
    echo "No controllers have found"
    return 0
  fi

  local query=''
  query+='Name:     \(.name)\n'
  query+='Address:  \(.address)'
  query+='\(if .is_default then "\nDefault:  \(.is_default)" else "" end)'
  query="[.[]|\"${query}\"]|join(\"\n\n\")"

  echo "${controllers}" | jq -cer "${query}" || return 1
}

# Shows the list of available devices filtered by
# the optionally given status.
# Arguments:
#  status: paired, connected or trusted
# Outputs:
#  A list of bluetooth devices.
list_devices () {
  local status="${1}"

  if [[ -n "${status}" ]] && [[ ! "${status}" =~ ^(paired|connected|trusted|bonded)$ ]]; then
    echo "Invalid status value"
    return 2
  fi

  local devices=''
  devices="$(find_devices "${status^}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to read devices"
    return 2
  fi

  local len=0
  len="$(count "${devices}")" || return 1

  if [[ ${len} -eq 0 ]]; then
    echo "No available devices have found"
    return 0
  fi

  local query=''
  query+='Name:     \(.name)\n'
  query+='Address:  \(.address)'
  query="[.[]|\"${query}\"]|join(\"\n\n\")"

  echo "${devices}" | jq -cer "${query}" || return 1
}

# Shows the data of the controller with the given
# address.
# Arguments:
#  address: the address of a controller
# Outputs:
#  A list of controller data.
show_controller () {
  local address="${1}"

  if [[ -z "${address}" ]]; then
    pick_controller || return $?
    [[ -n "${REPLY}" ]] && address="${REPLY}" || return 0
  fi

  local controller=''
  controller="$(find_controller "${address}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find controller ${address}"
    return 2
  fi

  local query=''
  query+='Name:          \(.name)\n'
  query+='Address:       \(.address)\n'
  query+='\(.is_public|if . then "Public:        \(.)\n" else "" end)'
  query+='alias:         \(.alias)\n'
  query+='Powered:       \(.powered)\n'
  query+='Discovering:   \(.discovering)\n'
  query+='Pairable:      \(.pairable)\n'
  query+='Discoverable:  \(.discoverable)\n'
  query+='Timeout:       \(.discoverable_timeout)\n'
  query+='Modalias:      \(.modalias)\n'
  query+='Class:         \(.class)'
  query+='\(.uuids|if . then "\nUUID:          \(.|join("\n               "))" else "" end)'
  
  echo "${controller}" | jq -cer ".[0]|\"${query}\"" || return 1
}

# Shows the data of the device with the given
# address.
# Arguments:
#  address: the address of a device
# Outputs:
#  A list of device data.
show_device () {
  local address="${1}"

  if [[ -z "${address}" ]]; then
    pick_device || return $?
    [[ -n "${REPLY}" ]] && address="${REPLY}" || return 0
  fi

  local device=''
  device="$(find_device "${address}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find device ${address}"
    return 2
  fi

  local query=''
  query+='Name:       \(.name)\n'
  query+='Address:    \(.address)\n'
  query+='Alias:      \(.alias)\n'
  query+='Icon:       \(.icon)\n'
  query+='\(.is_public|if . then "Public:     \(.)\n" else "" end)'
  query+='\(.rssi|if . then "RSSI:       \(.)\n" else "" end)'
  query+='\(.txpower|if . then "Power:      \(.)\n" else "" end)'
  query+='Connected:  \(.connected)\n'
  query+='Paired:     \(.paired)\n'
  query+='Bonded:     \(.bonded)\n'
  query+='Trusted:    \(.trusted)\n'
  query+='Blocked:    \(.blocked)\n'
  query+='Legacy:     \(.legacy_pairing)\n'
  query+='\(.modalias|if . then "Modalias:   \(.)\n" else "" end)'
  query+='Class:      \(.class)'
  query+='\(.uuids|if . then "\nUUID:       \(.|join("\n            "))" else "" end)'
  
  echo "${device}" | jq -cer ".[0]|\"${query}\"" || return 1
}

# Sets the default controller to the controller
# with the given address.
# Arguments:
#  address: the address of a controller
set_controller () {
  local address="${1}"

  if [[ -z "${address}" ]]; then
    pick_controller || return $?
    [[ -n "${REPLY}" ]] && address="${REPLY}" || return 0
  fi

  local controller=''
  controller="$(find_controller "${address}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find controller ${address}"
    return 2
  fi

  bluetoothctl select "${address}"

  if [[ $? -ne 0 ]]; then
    echo "Failed to set default controller"
    return 2
  fi

  echo "Default controller set to ${address}"
}

# Sets the default controller power to on/off.
# Arguments:
#  mode: on or off
set_power () {
  local mode="${1}"

  if [[ -z "${mode}" ]]; then
    echo "Missing the power mode value"
    return 2
  elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
    echo "Invalid power mode value"
    return 2
  fi

  if ! find_controller &> /dev/null; then
    echo "Unable to find default controller"
    return 2
  fi

  bluetoothctl power "${mode}" &> /dev/null

  if [[ $? -ne 0 ]]; then
    echo "Failed to set power mode to ${mode}"
    return 2
  fi

  echo "Power mode set to ${mode}"
}

# Sets scanning mode to on or off.
# Arguments:
#  mode: on or off
set_scan () {
  local mode="${1}"

  if [[ -z "${mode}" ]]; then
    echo "Missing scanning mode value"
    return 2
  elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
    echo "Invalid scanning mode value"
    return 2
  fi

  if ! find_controller &> /dev/null; then
    echo "Unable to find default controller"
    return 2
  fi

  # Collect any running scanning processes
  local query='.command|test("^bluetoothctl scan on")'
  query=".[]|select(${query})|.pid"

  local pids=''
  pids="$(ps aux | jc --ps | jq -cr "${query}")" || return 1

  # Clean any scanning processes before action
  if [[ -n "${pids}" ]]; then
    local pid=''
    while read -r pid; do
      kill "${pid}"
    done <<< "${pids}"
  fi

  if [[ "${mode}" == "on" ]]; then
    bluetoothctl scan on &> /dev/null &
  fi

  if [[ "${mode}" == "on" ]] && ! is_scanning_on ; then
    echo "Failed to set scanning mode to on"
    return 2
  elif [[ "${mode}" == "off" ]] && is_scanning_on ; then
    echo "Failed to set scanning mode to off"
    return 2
  fi

  echo "Scanning mode set to ${mode}"
}

# Sets the default controller discoverable mode to on/off.
# Arguments:
#  mode: on or off
set_discoverable () {
  local mode="${1}"

  if [[ -z "${mode}" ]]; then
    echo "Missing the discoverable mode value"
    return 2
  elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
    echo "Invalid discoverable mode value"
    return 2
  fi

  if ! find_controller &> /dev/null; then
    echo "Unable to find default controller"
    return 2
  fi

  bluetoothctl discoverable "${mode}" &> /dev/null

  if [[ $? -ne 0 ]]; then
    echo "Failed to set discoverable mode to ${mode}"
    return 2
  fi

  echo "Discoverable mode set to ${mode}"
}

# Sets the default controller pairable mode to on/off.
# Arguments:
#  mode: on or off
set_pairable () {
  local mode="${1}"

  if [[ -z "${mode}" ]]; then
    echo "Missing the pairable mode value"
    return 2
  elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
    echo "Invalid pairable mode value"
    return 2
  fi

  if ! find_controller &> /dev/null; then
    echo "Unable to find default controller"
    return 2
  fi

  bluetoothctl pairable "${mode}" &> /dev/null

  if [[ $? -ne 0 ]]; then
    echo "Failed to set pairable mode to ${mode}"
    return 2
  fi

  echo "Pairable mode set to ${mode}"
}

# Connects to the device with the given address.
# Arguments:
#  address: the address of a device
connect_device () {
  local address="${1}"

  if [[ -z "${address}" ]]; then
    pick_device || return $?
    [[ -n "${REPLY}" ]] && address="${REPLY}" || return 0
  fi

  local device=''
  device="$(find_device "${address}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find the device"
    return 2
  fi

  bluetoothctl pair "${address}" &> /dev/null &&
  bluetoothctl trust "${address}" &> /dev/null &&
  bluetoothctl connect "${address}" &> /dev/null

  if [[ $? -ne 0 ]]; then
    echo "Failed to connect device ${address}"
    return 2
  fi

  echo "Device ${address} has been connected"
}

# Disconnects the device with the given address.
# Arguments:
#  address: the address of a device
disconnect_device () {
  local address="${1}"

  if [[ -z "${address}" ]]; then
    pick_device || return $?
    [[ -n "${REPLY}" ]] && address="${REPLY}" || return 0
  fi

  local device=''
  device="$(find_device "${address}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find the device"
    return 2
  fi

  bluetoothctl disconnect "${address}" &> /dev/null

  if [[ $? -ne 0 ]]; then
    echo "Failed to disconnect device ${address}"
    return 2
  fi

  echo "Device ${address} has been disconnected"
}

# Removes the device with the given address.
# Arguments:
#  address: the address of a device
remove_device () {
  local address="${1}"

  if [[ -z "${address}" ]]; then
    pick_device || return $?
    [[ -n "${REPLY}" ]] && address="${REPLY}" || return 0
  fi

  local device=''
  device="$(find_device "${address}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find the device"
    return 2
  fi

  bluetoothctl remove "${address}" &> /dev/null

  if [[ $? -ne 0 ]]; then
    echo "Failed to remove device ${address}"
    return 2
  fi

  echo "Device ${address} has been removed"
}

# Restarts the bluetooth service.
# Arguments:
#  None
restart_bluetooth () {
  rfkill block bluetooth &&
  rfkill unblock bluetooth &&
  sudo modprobe -r btusb &&
  sudo modprobe -r btintel &&
  sudo modprobe btintel &&
  sudo modprobe btusb &&
  sudo systemctl restart bluetooth.service

  if [[ $? -ne 0 ]]; then
    echo "Failed to restart the bluetooth service"
    return 2
  fi

  echo "Bluetooth service has been restarted"
}

