#!/bin/bash

set -o pipefail

source /opt/stack/utils

# Prints the current memory usage and utilization.
run () {
  # Read current memory usage and utilization
  local stats=0
  stats="$(top -bn1 | awk '/MiB Mem/{printf "%05d,%f", int($8), $8/$4}')"

  local usage=0
  usage="$(echo "${stats}" | cut -d ',' -f 1)"
  
  local util=0
  util="$(echo "${stats}" | cut -d ',' -f 2)"

  local util_color='B2E39C'
  if is_true "25 < ${util} <= 50"; then
    util_color="F27D52"
  elif is_true "50 < ${util} <= 75"; then
    util_color="E5758A"
  elif is_true "${util} > 75"; then
    util_color="CB2C31"
  fi

  echo "${usage}MiB%{F#00000000}:%{F-}%{F#${util_color}}●%{F-}"
}

run "$@"

