#!/bin/bash

# Returns the current audio output status.
run () {
  local status=''
  status="$(amixer get Master | grep % | awk '{
    gsub(/(\[|\])/, "", $5)
    gsub(/(\[|\])/, "", $6)

    if ($6 == "off") {
      print "Muted"
    } else {
      print $5
    }

    exit
  }')"
  
  echo "${status}"
}

run "$@"

