#!/bin/bash

set -Eeo pipefail

source /opt/stack/commons/validators.sh

CLOCK_SETTINGS="${HOME}/.config/stack/clock.json"

# Prints the current time endlessly.
run () {
  local mode='24h'
  local precision='mins'

  # Read the clock precision and format settings
  if file_exists "${CLOCK_SETTINGS}"; then
    local settings=''
    settings="$(jq -cr '.' "${CLOCK_SETTINGS}")"

    mode="$(echo "${settings}" | jq -cr '.time_mode')"
    precision="$(echo "${settings}" | jq -cr '.time_precision')"
  fi

  local hour='H'
  local postfix=''
  if equals "${mode}" '12h'; then
    hour='I'
    postfix='%p'
  fi

  local format=''
  local refresh=0.5

  case "${precision}" in
    'nanos')
      format="%${hour}:%M:%S.%2N"
      refresh=0.08
      ;;
    'secs') format="%${hour}:%M:%S";;
    *) format="%${hour}:%M";;
  esac

  format="${format}${postfix:+ ${postfix}}"

  # Start printing the time with the given refresh rate
  while true; do
    echo "$(date +"${format}")"
    sleep ${refresh}
  done
}

run "$@"

