#!/bin/bash

set -Eeo pipefail

source /opt/stack/commons/math.sh
source /opt/stack/commons/validators.sh

UPDATES_FILE=/tmp/updates

# Reads the special update file which should contain
# a integer value, where 0 means the system is up to
# date, < 0 means the system is now updating, > 0
# means that many outdated packages and if the file
# is missing means system is up to date.
run () {
  local output='Ready'
  local color='B2E39C'
  
  if file_exists "${UPDATES_FILE}"; then
    local packages=''
    packages="$(< "${UPDATES_FILE}")"

    if is_not_integer "${packages}"; then
      output='Err!'
    elif is_true "${packages} < 0"; then
      output='Updating'
      color='2222FF'
    elif is_true "${packages} > 0"; then
      output="$(printf '%03d' ${packages})"
      color='F27D52'
    fi
  fi

  if is_not_empty "${color}"; then
    output="${output}%{F#00000000}:%{F-}%{F#${color}}●%{F-}"
  fi

  echo "${output}"
}

run "$@"

