#!/bin/bash

rm -f /etc/arch-release

cat /etc/stack-release > /usr/lib/os-release

if [[ -f /etc/lsb-release ]]; then
  printf '%s\n' \
    'DISTRIB_ID="Stack"' \
    'DISTRIB_RELEASE="rolling"' \
    'DISTRIB_DESCRIPTION="Stack Linux"' > /etc/lsb-release
fi
