#!/bin/bash

set -o pipefail

source /opt/stack/utils

SETTINGS_FILE="${CONFIG_HOME}/power.json"

# Finds the ac power adapter data.
# Outputs:
#  A json object of ac power data.
find_adapter () {
  acpi -a | jc --acpi | jq -cer '.[0]' || return 1
}

# Finds the battery power data.
# Outputs:
#  A json object of battery power data.
find_battery () {
  local query=''
  query+='if length > 0 then .[0] else "" end'

  acpi -b -i | jc --acpi | jq -cer "${query}" || return 1
}

# Shows a menu asking the user to select a power handler.
# Outputs:
#  A menu of power handlers.
pick_power_handler () {
  local handlers=''
  handlers+='{"key":"power", "value":"power"},'
  handlers+='{"key":"reboot", "value":"reboot"},'
  handlers+='{"key":"suspend", "value":"suspend"},'
  handlers+='{"key":"lid", "value":"lid"},'
  handlers+='{"key":"docked", "value":"docked"}'
  handlers="[${handlers}]"

  pick_one 'Select power handler:' "${handlers}" vertical || return $?
}

# Checks if the given power handler is a valid one.
# Arguments:
#  handler: the name of a power handler
# Returns:
#  0 if it is valid otherwise 1.
is_power_handler () {
  local handler="${1}"
  
  if not_match "${handler}" '^(power|reboot|suspend|lid|docked)$'; then
    return 1
  fi

  return 0
}

# Checks if the given power handler is not valid.
# Arguments:
#  handler: the name of a power handler
# Returns:
#  0 if it is not valid otherwise 1.
is_not_power_handler () {
  is_power_handler "${1}" && return 1 || return 0
}

# Shows a menu asking the user to select a power action.
# Outputs:
#  A menu of power actions.
pick_power_action () {
  local actions=''
  actions+='{"key":"poweroff", "value":"poweroff"},'
  actions+='{"key":"reboot", "value":"reboot"},'
  actions+='{"key":"suspend", "value":"suspend"},'
  actions+='{"key":"ignore", "value":"ignore"}'
  actions="[${actions}]"

  pick_one 'Select an action:' "${actions}" vertical || return $?
}

# Checks if the given power action is a valid one.
# Arguments:
#  action: the name of a power action
# Returns:
#  0 if it is valid otherwise 1.
is_power_action () {
  local action="${1}"
  
  if not_match "${action}" '^(poweroff|reboot|suspend|ignore)$'; then
    return 1
  fi

  return 0
}

# Checks if the given power action is not valid.
# Arguments:
#  action: the name of a power action
# Returns:
#  0 if it is not valid otherwise 1.
is_not_power_action () {
  is_power_action "${1}" && return 1 || return 0
}

# Resolves the corresponding logind config option
# for the given power handler.
# Arguments:
#  handler: the name of a power handler
# Outputs:
#  A logind config option.
convert_handler_to_option () {
  local handler="${1}"

  local option=''

  case "${handler}" in
    'power') option='HandlePowerKey';;
    'reboot') option='HandleRebootKey';;
    'suspend') option='HandleSuspendKey';;
    'lid') option='HandleLidSwitch';;
    'docked') option='HandleLidSwitchDocked';;
    *)
      echo 'Invalid or unknown power handler'
      return 2;;
  esac

  echo "${option}"
}

# Saves the interval time of the screen saver into settings.
# Arguments:
#  interval: the interval time in mins or 0
save_screen_saver_to_settings () {
  local interval="${1}"

  local settings='{}'
  local screensaver="{\"interval\": ${interval}}"

  if file_exists "${SETTINGS_FILE}"; then
    settings="$(jq -e ".screensaver = ${screensaver} " "${SETTINGS_FILE}")" || return 1
  else
    settings="$(echo "{\"screensaver\": ${screensaver}}" | jq -e '.')" || return 1
  fi

  mkdir -p "${CONFIG_HOME}"
  echo "${settings}" > "${SETTINGS_FILE}"
}

# Checks if the given value is a valid screensaver interval.
# Arguments:
#  interval: an integer value
# Returns:
#  0 if interval is valid otherwise 1.
interval_is_with_in_range () {
  local interval="${1}"

  if [[ ${interval} -lt 0 ]] || [[ ${interval} -gt 60 ]]; then
    return 1
  fi

  return 0
}

# Checks if the given value is not valid screensaver interval.
# Arguments:
#  interval: an integer value
# Returns:
#  0 if interval is not valid otherwise 1.
interval_is_out_of_range () {
  interval_is_with_in_range "${1}" && return 1 || return 0
}

# Checks if the given value is a valid charging limit.
# Arguments:
#  limit: a percentage integer value
# Returns:
#  0 if value is valid otherwise 1.
charge_limit_is_with_in_range () {
  local limit="${1}"

  if [[ ${limit} -lt 0 ]] || [[ ${limit} -gt 100 ]]; then
    return 1
  fi

  return 0
}

# Checks if the given value is not valid charging limit.
# Arguments:
#  limit: a percentage integer value
# Returns:
#  0 if value is not valid otherwise 1.
charge_limit_is_out_of_range () {
  charge_limit_is_with_in_range "${1}" && return 1 || return 0
}

