#!/bin/bash

set -o pipefail

source /opt/stack/utils
source /opt/stack/trash/commands

# Shows the help message.
# Arguments:
#  mode: loop or once
# Outputs:
#  A long help message.
show_help () {
  local mode="${1:-"once"}"

  if [[ "${mode}" == "once" ]]; then
    echo 'Usage: trash [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
    
    echo -e '\nOPTIONS'
    printf ' %-10s %s\n' \
      '-h' 'Show this help message.' \
      '-q' 'Stay quiet and do not play beep sounds.'
  
    echo -e '\nCOMMANDS'
  else
    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'

    echo -e '\nCOMMANDS'
    printf ' %-25s %s\n' \
      'help' 'Show this help message.'
  fi

  printf ' %-25s %s\n' \
    'list files' 'List all trashed files.' \
    'list files <days>' 'List files trashed within the given days.' \
    'list files +<days>' 'List files trashed more than the given days ago.' \
    'list files <date>' 'List files trashed at a certain date.' \
    '' '' \
    'restore files [<path>]' 'Restore files starting from / or the given path.' \
    'remove files [<paths>]' 'Remove the given trashed files.' \
    '' '' \
    'empty files' 'Remove all trashed files.' \
    'empty files <days>' 'Remove files trashed more than the given days ago.'
}

run () {
  local opt=''

  while getopts 'hq' opt; do
    case "${opt}" in
     'h')
        show_help once
        return 0;;
     'q') QUIET='true';;
     *)
      echo 'Ooops, invalid or unknown option'
      $(exit 2) || beep
      return $?;;
    esac
  done

  shift $((OPTIND-1))

  local mode='once'
  if [[ $# -eq 0 ]]; then
    mode='loop'
    clear
  fi

  while true; do
    if [[ "${mode}" == "loop" ]]; then
      prompt trash
    else
      REPLY="$@"
    fi

    set -f
    set_separator line
    local args=($(xargs -n1 <<< "${REPLY}"))
    restore_separator && set +f
    REPLY=''

    local cmd="${args[0]}"
    local obj="${args[1]}"

    if [[ "${mode}" == "loop" ]]; then
      case "${cmd}${obj:+ ${obj}}" in
        'help') clear && show_help loop && continue;;
        'clear') clear && continue;;
        'quit') break;;
        '') continue;;
      esac
    fi

    case "${cmd}${obj:+ ${obj}}" in
      'list files') list_files "${args[2]}";;
      'restore files') restore_files "${args[2]}" && beep;;
      'remove files') remove_files "${args[@]:2}" && beep;;
      'empty files') empty_files "${args[2]}" && beep;;  
      *)
        echo 'Ooops, invalid or unknown command!'
        $(return 2);;
    esac || beep

    local exit_code=$?
    if [[ "${mode}" == "once" ]]; then
      return ${exit_code}
    fi
  done

  clear
}

run "$@"

