#!/bin/bash

set -o pipefail

source /opt/stack/utils
source /opt/stack/langs/commands

# Shows the help message.
# Arguments:
#  None
# Outputs:
#  A long help message.
show_help () {
  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'

  echo -e '\nCOMMANDS'
  printf ' %-35s %s\n' \
    'help' 'Show this help message.' \
    '' '' \
    'show status' 'Show the system locale and keyboard status.' \
    '' '' \
    'set language [<language>]' 'Set the system language.' \
    'set keymap [<map>]' 'Set the keyboard virtual console keymap.' \
    'set options [<value>]' 'Set a keyboard layout options.' \
    'set model [<name>]' 'Set the model of the keyboard.' \
    '' '' \
    'set locale <name> [<locale>]' 'Set a locale variable, where name could be' \
    '' 'ctype, numeric, time, collate, monetary,' \
    '' 'messages, paper, name, address, telephone,' \
    '' 'measurement, identification.' \
    'add locale [<locale>]' 'Add a locale to the system locales.' \
    'remove locale [<locale>]' 'Remove a locale from the system locales.' \
    '' '' \
    'add layout [<language>]' 'Add a keyboard layout language.' \
    'remove layout [<language>]' 'Remove a keyboard layout language.' \
    'order layouts' 'Set the order of keyboard layouts.'
}

loop () {
  clear

  while true; do
    prompt langs && history -s "${REPLY}"

    set -f
    set_separator line
    local args=($(xargs -n1 <<< "${REPLY}"))
    restore_separator && set +f

    local cmd="${args[0]}"
    local obj="${args[1]}"

    case "${cmd}${obj:+ ${obj}}" in
      'help') show_help;;
      'show status') show_status;;
      'set keymap') set_keymap "${args[2]}";;
      'set language') set_language "${args[2]}";;
      'set locale') set_locale "${args[2]}" "${args[3]}";;
      'set options') set_options "${args[2]}";;
      'set model') set_model "${args[2]}";;
      'add locale') add_locale "${args[2]}";;
      'add layout') add_layout "${args[2]}";;
      'remove locale') remove_locale "${args[2]}";;
      'remove layout') remove_layout "${args[2]}";;
      'order layouts') order_layouts;;
      'clear') clear && continue;;
      'quit') break;;
      '') continue;;
      *)
        echo 'Ooops, invalid or unknown command!'
        $(return 2);;
    esac && success || fail

    REPLY=''
  done

  clear
}

loop

