#!/usr/bin/env bash

show_apps_menu () {
  rofi -show drun
}

show_run_menu () {
  rofi -show run
}

show_windows_menu () {
  rofi -show window
}

show_emoji_menu () {
  rofi -show emoji
}

show_power_menu () {
  local SD=" Shutdown"
  local RB=" Reboot"
  local SP="  Suspend"
  local LK=" Lock"
  local LO=" Logout"

  local HIDE_PROMT="inputbar {children: [entry];}"
  local EXACT_LINES="listview {lines: 6;}"

  local CHOSEN=$(printf "$SD\n$RB\n$SP\n$LK\n$LO" | rofi -dmenu -i -theme-str "${HIDE_PROMT} ${EXACT_LINES}")

  case "$CHOSEN" in
    "$SD") power shutdown;;
    "$RB") power reboot;;
    "$SP") power suspend;;
    "$LK") power lock;;
    "$LO") power logout;;
    *) exit 1;;
  esac
}

case "$1" in
 "apps") show_apps_menu;;
 "run") show_run_menu;;
 "windows") show_windows_menu;;
 "emoji") show_emoji_menu;;
 "power") show_power_menu;;
 *) abort "Missing or invalid launch menu";;
esac
