#!/bin/bash

set -o pipefail

source /opt/stack/utils
source /opt/stack/networks/commands

# Shows the help message.
# Arguments:
#  mode: loop or once
# Outputs:
#  A long help message.
show_help () {
  local mode="${1:-"once"}"

  if [[ "${mode}" == "once" ]]; then
    echo 'Usage: networks [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
    
    echo -e '\nOPTIONS'
    printf ' %-10s %s\n' \
      '-h' 'Show this help message.' \
      '-q' 'Stay quiet and do not play beep sounds.'
  
    echo -e '\nCOMMANDS'
  else
    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'

    echo -e '\nCOMMANDS'
    printf ' %-36s %s\n' \
      'help' 'Show this help message.'
  fi

  printf ' %-36s %s\n' \
    'show status' 'Show the current status of networking.' \
    'show device [<name>]' 'Show the data of a device.' \
    'show connection [<name>]' 'Show the data of a connection.' \
    '' '' \
    'list devices' 'List the network devices.' \
    'list connections' 'List the network connections.' \
    'list wifis [<device>] [<signal>]' 'Detect wifi networks with a min signal.' \
    '' '' \
    'up device [<name>]' 'Enable a network device.' \
    'down device [<name>]' 'Disable a network device.' \
    'remove device [<name>]' 'Remove a software network device.' \
    '' '' \
    'up connection [<name>]' 'Enable a connection.' \
    'down connection [<name>]' 'Disable a connection.' \
    'add connection eth|wifi|vpn' 'Add an ethernet, wifi or vpn connection.' \
    'remove connection [<name>]' 'Remove a connection.' \
    '' '' \
    'add proxy <name>' 'Add a new proxy server profile.' \
    'remove proxy [<name>]' 'Remove a proxy server profile.' \
    'list proxies' 'List all proxy server profiles.' \
    'set proxy [<name>]' 'Applies proxy server settings.' \
    'unset proxy' 'Disables proxy server settings.' \
    '' '' \
    'power network on|off' 'Set the system network to on or off.' \
    'power wifi on|off' 'Set the wifi device to on or off.'
}

run () {
  local opt=''

  while getopts 'hq' opt; do
    case "${opt}" in
     'h')
        show_help once
        return 0;;
     'q') QUIET='true';;
     *)
      echo 'Ooops, invalid or unknown option'
      $(exit 2) || beep
      return $?;;
    esac
  done

  shift $((OPTIND-1))

  local mode='once'
  if [[ $# -eq 0 ]]; then
    mode='loop'
    clear
  fi

  while true; do
    if [[ "${mode}" == "loop" ]]; then
      prompt networks && history -s "${REPLY}"
    else
      REPLY="$@"
    fi

    set -f
    set_separator line
    local args=($(xargs -n1 <<< "${REPLY}"))
    restore_separator && set +f
    REPLY=''

    local cmd="${args[0]}"
    local obj="${args[1]}"

    if [[ "${mode}" == "loop" ]]; then
      case "${cmd}${obj:+ ${obj}}" in
        'help') show_help loop && continue;;
        'clear') clear && continue;;
        'quit') break;;
        '') continue;;
      esac
    fi

    case "${cmd}${obj:+ ${obj}}" in
      'show status') show_status;;
      'show device') show_device "${args[2]}";;
      'show connection') show_connection "${args[2]}";;
      'list devices') list_devices;;
      'list connections') list_connections;;
      'list wifis') list_wifis "${args[2]}" "${args[3]}";;
      'list proxies') list_proxies;;
      'power network') power_network "${args[2]}" && beep;;
      'power wifi') power_wifi "${args[2]}" && beep;;
      'up device') up device "${args[2]}" && beep;;
      'down device') down device "${args[2]}" && beep;;
      'up connection') up connection "${args[2]}" && beep;;
      'down connection') down connection "${args[2]}" && beep;;
      'add connection eth') add_ethernet_connection && beep;;
      'add connection wifi') add_wifi_connection && beep;;
      'add connection vpn') add_vpn_connection && beep;;
      'add proxy') add_proxy "${args[2]}" && beep;;
      'remove device') remove_device "${args[2]}" && beep;;
      'remove connection') remove_connection "${args[2]}" && beep;;
      'remove proxy') remove_proxy "${args[2]}" && beep;;
      'set proxy') set_proxy "${args[2]}" && beep;;
      'unset proxy') unset_proxy && beep;;
      *)
        echo 'Ooops, invalid or unknown command!'
        $(return 2);;
    esac || beep

    local exit_code=$?
    if [[ "${mode}" == "once" ]]; then
      return ${exit_code}
    fi
  done

  clear
}

run "$@"

