#!/bin/python3

import sys
import pam
from getpass import getuser, getpass

username = getuser()
password = getpass()

if not pam.authenticate(username, password):
  print('not ok')
  sys.exit(1)

print('ok')
sys.exit(0)