#!/bin/bash

set -o pipefail

# Read parameters coming from dunst
appname="${1}"
summary="${2}"
body="${3}"
urgency="${5}"

sound='normal'

if [[ "${urgency}" == "CRITICAL" ]]; then
  sound='critical'
fi

settings_file="${HOME}/.config/stack/notifications.json"

volume="$(jq -cer '.volume' "${settings_file}")"

if [[ $? -ne 0 ]]; then
  volume=0.8
fi

pw-play --volume="${volume}" "/usr/share/sounds/dunst/${sound}.wav"
