#!/bin/bash

set -Eeo pipefail

source /opt/stack/commons/validators.sh

# Applies various hook actions to handle user experience
# during suspend and wake up of the system.
# Arguments:
#  phase:  pre, post
#  action: suspend, reboot etc.
run () {
  local phase="${1}"
  local action="${2}"

  # Delay suspend to give some time to the locker to take action
  if equals "${phase}" 'pre' && equals "${action}" 'suspend'; then
    sleep 2
  fi

  # On resume prompt for authentication
  if equals "${phase}" 'post'; then
    pkill -x -USR2 xsecurelock
  fi
}

run "$@"
