#!/usr/bin/env bash

source /opt/stack/utils

require "libpulse"
require "jq"

prompt () {
  local YELLOW=$'\e[0;33m'
  local GREEN=$'\e[0;32m'
  local MAGENTA=$'\e[0;35m'
  local RS=$'\e[m'
  local FG=$YELLOW

  local SINK=$(pactl --format=json list sinks | jq -r -M ".[0].active_port")
  local DB=$(pactl --format=json list sinks | jq -r -M '.[0].volume | keys[0] as $k | (.[$k].db)' | awk '{print $1$2}')
  
  local SC="$MAGENTA"
  [[ "$DB" =~ ^(-|0.00) ]] && SC="$GREEN"

  read -rep "[audio:$FG${SINK}$RS $SC${DB}$RS] " REPLY
}

show_status () {
  local FRM="%-32s\t%s\n"

  pactl info | awk -v f="$FRM" -F: '{printf f, $1":", $2}'
  pactl stat | awk -v f="$FRM" -F: '{printf f, $1":", $2}'
}

show_card () {
  local CARD=$1

  if [ -z "$CARD" ]; then
    echo "Missing card name or id argument"
    return 1
  fi

  local FIELD="name"
  local VALUE="\"${CARD}\""

  if [[ "$CARD" =~ ^[0-9]+$ ]]; then
    FIELD="index"
    VALUE=$CARD
  fi

  local QUERY=".[] | select(.${FIELD}==${VALUE})"

  pactl --format=json list cards | jq -e -M "$QUERY" ||
    echo "Cannot find audio card with $FIELD $CARD"
}

list_cards () {
  local FRM="%-3s %-35s %-4s %-15s %s\n"
  printf "$FRM" "ID" "NAME" "BUS" "MODEL" "VENDOR"

  local QUERY='.[]|"\(.index),'
  QUERY+='\(.name),'
  QUERY+='\(.properties."device.bus"),'
  QUERY+='\(.properties."device.nick"),'
  QUERY+='\(.properties."device.vendor.name")"'

  pactl --format=json list cards | jq -r "$QUERY" |
    awk -v f="$FRM" -F, '{printf f,$1,$2,$3,$4,$5}'
}

list_profiles () {
  local CARD=$1

  if [ -z "$CARD" ]; then
    echo "Missing card name or id argument"
    return 1
  fi

  local FIELD="name"
  local VALUE="\"${CARD}\""

  if [[ "$CARD" =~ ^[0-9]+$ ]]; then
    FIELD="index"
    VALUE=$CARD
  fi

  local QUERY=".[] | select(.${FIELD}==${VALUE})"

  if pactl --format=json list cards | jq -e "$QUERY" > /dev/null; then
    QUERY+='| .profiles'
    QUERY+='| to_entries[]'
    QUERY+='| "\(.key),\(.value.description)"'

    local FRM="%-46s %s\n"
    printf "$FRM" "KEY" "DESCRIPTION"

    pactl --format=json list cards | jq -M -r "$QUERY" |
      awk -v f="$FRM" -F, '{printf f,$1,$2}'
  else
    echo "Cannot find audio card with $FIELD $CARD"
  fi
}

set_profile () {
  local CARD=$1
  local PROFILE=$2

  if [ -z "$CARD" ]; then
    echo "Missing the card argument"
    return 1
  fi

  if [ -z "$PROFILE" ]; then
    echo "Missing the profile argument"
    return 1
  fi

  pactl set-card-profile "$CARD" "$PROFILE" &> /dev/null &&
    echo "Audio profile has been set to $PROFILE" ||
    echo "Something went wrong setting the audio profile"
}

help () {
  local FRM=" %-28s\t%s\n"

  echo "Usage: COMMAND [OBJECT] [ARGUMENTS]..."

  echo -e "\nCOMMANDS"
  printf "$FRM" \
    "help" "Show this help message." \
    "show status" "Show an overall report of the system's audio." \
    "show card <name|id>" "Show data for the card with the given name or id." \
    "" "" \
    "list cards" "List all the audio cards plugged to the system." \
    "list profiles <name|id>" "List the profiles of the given audio card." \
    "" "" \
    "set profile <card> <profile>" "Set the audio profile of the given card."

  echo -e "\nOBJECTS"
  printf "$FRM" \
    "status" "The status of the system's audio." \
    "card" "An audio card." \
    "profile" "An audio profile of a card."
}

loop () {
  clear

  while true; do
    prompt && history -s "$REPLY"

    set -f
    local OLD_IFS=$IFS && IFS=$'\n'
    local CMD=($(xargs -n1 <<< "$REPLY"))
    IFS=$OLD_IFS && set +f

    if [ "${CMD[0]}" = "help" ]; then
      help
      continue
    elif [ "${CMD[0]}" = "clear" ]; then
      clear
      continue
    elif [ "${CMD[0]}" = "quit" ]; then
      break
    elif [ -z "${CMD[0]}" ]; then
      continue
    fi

    case "${CMD[0]}" in
      "show")
        case "${CMD[1]}" in
          "status") show_status;;
          "card") show_card "${CMD[2]}";;
          *) echo "Unknown or invalid command: '$REPLY'";;
        esac;;
      "list")
        case "${CMD[1]}" in
          "cards") list_cards;;
          "profiles") list_profiles "${CMD[2]}";;
          *) echo "Unknown or invalid command: '$REPLY'";;
        esac;;
      "set")
        case "${CMD[1]}" in
          "profile") set_profile "${CMD[2]}" "${CMD[3]}";;
          *) echo "Unknown or invalid command: '$REPLY'";;
        esac;;
      *) echo "Unknown or invalid command: '$REPLY'";; 
    esac
  done

  clear
}

loop
