#!/usr/bin/env bash

set -o pipefail

source /opt/stack/utils

require "libpulse"
require "jq"

prompt () {
  local CARDS=$(pactl --format=json list short cards | jq -cer '.|length' || echo "err:$?")

  [[ "$CARDS" =~ ^err: ]] &&
    echo "Unable to find audio cards" &&
    read -rep "[audio:${RE}failed$RS] " REPLY &&
    return 1
  
  [ ! $CARDS -gt 0 ] &&
    read -rep "[audio:${YE}none$RS] " REPLY &&
    return 1

  local DEFAULT=$(pactl --format=json info | jq -cer ".default_sink_name" || echo "err:$?")

  [[ "$DEFAULT" =~ ^err: ]] &&
    echo "Unable to resolve default output" &&
    read -rep "[audio:${RE}failed$RS] " REPLY &&
    return 1

  local QUERY='.[] | select(.name == "'$DEFAULT'")'
  local SINK=$(pactl --format=json list sinks | jq -cer "$QUERY" || echo "err:$?")

  [[ "$SINK" =~ ^err: ]] &&
    echo "Unable to retrieve default output data" &&
    read -rep "[audio:${RE}failed$RS] " REPLY &&
    return 1

  local PORT=$(echo "$SINK" | jq -cr '.active_port')
  local MUTE=$(echo "$SINK" | jq -cr '.mute')
  local DB=$(echo "$SINK" | jq -cr '.volume | keys[0] as $k | .[$k].db' | awk '{print $1$2}')

  local STATUS="$YE${PORT}$RS"

  if [ "$MUTE" = "true" ]; then
    STATUS+=" ${MA}muted$RS"
  elif [[ "$DB" =~ ^(-|0.00) ]]; then
    STATUS+=" $GR${DB}$RS"
  else
    STATUS+=" $MA${DB}$RS"
  fi

  read -rep "[audio:${STATUS}] " REPLY
}

show_status () {
  local QUERY='("'
  QUERY+='Server:    \(.server_name)\n'
  QUERY+='Path:      \(.server_string)\n'
  QUERY+='Version:   \(.server_version)\n'
  QUERY+='Local:     \(.is_local)\n'
  QUERY+='Client:    \(.client_index)\n'
  QUERY+='Sample:    \(.default_sample_specification)\n'
  QUERY+='Channels:  \(.default_channel_map)\n'
  QUERY+='Sink:      \(.default_sink_name)\n'
  QUERY+='Sources:   \(.default_source_name)\n'
  QUERY+='Cookie:    \(.cookie)\n")'

  pactl --format=json info | jq -cer "$QUERY" ||
    echo -e "Unable to retrieve audio server info\n"
  
  QUERY='.[] | ("'
  QUERY+='Card:      \(.index)\n'
  QUERY+='Name:      \(.name)\n'
  QUERY+='Model:     \(.properties."device.nick")\n'
  QUERY+='Vendor:    \(.properties."device.vendor.name")\n'
  QUERY+='Product:   \(.properties."device.product.name")\n'
  QUERY+='Driver:    \(.driver)\n'
  QUERY+='Form:      \(.properties."device.form_factor")\n'
  QUERY+='Bus:       \(.properties."device.bus")\n'
  QUERY+='Profile:   \(.active_profile)\n")'

  pactl --format=json list cards | jq -cer "$QUERY" | head -n -1 ||
    echo "Unable to retrieve audio cards"
}

show_card () {
  local CARD=$1

  if [ -z "$CARD" ]; then
    echo "Missing name or id argument"
    return 1
  fi

  local FIELD="name"
  local VALUE="\"${CARD}\""

  if [[ "$CARD" =~ ^[0-9]+$ ]]; then
    FIELD="index"
    VALUE=$CARD
  fi

  local QUERY=".[] | select(.${FIELD}==${VALUE})"
  CARD=$(pactl --format=json list cards | jq -cer "$QUERY" || echo "err:$?")

  [[ "$CARD" =~ ^err: ]] &&
    echo "Unable to get data for card with $FIELD $VALUE" &&
    return 1

  QUERY='("ID:                 \(.index)\n'
  QUERY+='Name:               \(.name)\n'
  QUERY+='Driver:             \(.driver)\n'
  QUERY+='Owner:              \(.owner_module)\n'
  QUERY+='Enum API:           \(.properties."device.enum.api")\n'
  QUERY+='Device API:         \(.properties."device.api")\n'
  QUERY+='Media Class:        \(.properties."media.class")\n'
  QUERY+='API Alsa Path:      \(.properties."api.alsa.path")\n'
  QUERY+='API Alsa Card:      \(.properties."api.alsa.card")\n'
  QUERY+='API Alsa Card Name: \(.properties."api.alsa.card.name")\n'
  QUERY+='Card Long Name:     \(.properties."api.alsa.card.longname")\n'
  QUERY+='Usec:               \(.properties."device.plugged.usec")\n'
  QUERY+='Bus Path:           \(.properties."device.bus_path")\n'
  QUERY+='SysFS Path:         \(.properties."sysfs.path")\n'
  QUERY+='Bus:                \(.properties."device.bus")\n'
  QUERY+='Subsystem:          \(.properties."device.subsystem")\n'
  QUERY+='Vendor ID:          \(.properties."device.vendor.id")\n'
  QUERY+='Vendor Name:        \(.properties."device.vendor.name")\n'
  QUERY+='Product ID:         \(.properties."device.product.id")\n'
  QUERY+='Product Name:       \(.properties."device.product.name")\n'
  QUERY+='Form Factor:        \(.properties."device.form_factor")\n'
  QUERY+='Device Name:        \(.properties."device.name")\n'
  QUERY+='Description:        \(.properties."device.description")\n'
  QUERY+='Model:              \(.properties."device.nick")\n'
  QUERY+='Use ACP:            \(.properties."api.alsa.use-acp")\n'
  QUERY+='Auto Profile:       \(.properties."api.acp.auto-profile")\n'
  QUERY+='Auto Port:          \(.properties."api.acp.auto-port")\n'
  QUERY+='Reserve Devicel:    \(.properties."api.dbus.ReserveDevice1")\n'
  QUERY+='Factory:            \(.properties."factory.id")\n'
  QUERY+='Client ID:          \(.properties."client.id")\n'
  QUERY+='Object ID:          \(.properties."object.id")\n'
  QUERY+='Object Serial:      \(.properties."object.serial")\n'
  QUERY+='Object Path:        \(.properties."object.path")\n'
  QUERY+='Alsa Card:          \(.properties."alsa.card")\n'
  QUERY+='Active Profile:     \(.active_profile)")'

  echo "$CARD" | jq -cr "$QUERY"

  echo -e "\nProfiles:"
  echo "$CARD" | jq -cr '.profiles | " \(keys[])"' ||
    echo " Unable to resolve audio profiles"

  echo -e "\nPorts:"
  echo "$CARD" | jq -cr '.ports | to_entries[] | " \(.key) [\(.value.type)]"' ||
    echo " Unable to resolve audio ports"
}

list_cards () {
  local QUERY='.[] | ("\n'
  QUERY+='ID:      \(.index)\n'
  QUERY+='Name:    \(.name)\n'
  QUERY+='Model:   \(.properties."device.nick")\n'
  QUERY+='Vendor:  \(.properties."device.vendor.name")\n'
  QUERY+='Bus:     \(.properties."device.bus")")'

  local CARDS=$(pactl --format=json list cards | jq -cer "$QUERY" || echo "err:$?")

  [[ "$CARDS" =~ ^err: ]] &&
    echo "Unable to retieve audio cards" &&
    return 1

  echo "$CARDS" | tail -n +2
}

list_profiles () {
  local CARD=$1

  if [ -z "$CARD" ]; then
    echo "Missing name or id argument"
    return 1
  fi

  local FIELD="name"
  local VALUE="\"${CARD}\""

  if [[ "$CARD" =~ ^[0-9]+$ ]]; then
    FIELD="index"
    VALUE=$CARD
  fi

  local QUERY=".[] | select(.${FIELD}==${VALUE})"
  CARD=$(pactl --format=json list cards | jq -cer "$QUERY" || echo "err:$?")

  [[ "$CARD" =~ ^err: ]] &&
    echo "Unable to retieve card with $FIELD $VALUE" &&
    return 1

  echo "$CARD" | jq -cr '.profiles | keys[]'
}

list_outputs () {
  local QUERY='.[] |= . + {"sink": .name} |'
  QUERY+='map((.ports[] + {index, sink, mute, properties})) |'
  QUERY+='.[] | ("\n'
  QUERY+='ID:      \(.index)\n'
  QUERY+='Sink:    \(.sink)\n'
  QUERY+='Name:    \(.name)\n'
  QUERY+='Model:   \(.properties."device.nick")\n'
  QUERY+='Type:    \(.type)\n'
  QUERY+='Mute:    \(.mute)\n'
  QUERY+='Status:  \(.availability)")'

  local SINKS=$(pactl --format=json list sinks | jq -cer "$QUERY" || echo "err:$?")

  [[ "$SINKS" =~ ^err: ]] &&
    echo "Unable to retieve audio outputs" &&
    return 1
  
  echo "$SINKS" | tail -n +2
}

list_inputs () {
  local QUERY='.[] |= . + {"source": .name} |'
  QUERY+='map((.ports[] + {index, source, mute, properties})) |'
  QUERY+='.[] | ("\n'
  QUERY+='ID:      \(.index)\n'
  QUERY+='Source:  \(.source)\n'
  QUERY+='Name:    \(.name)\n'
  QUERY+='Model:   \(.properties."device.nick")\n'
  QUERY+='Type:    \(.type)\n'
  QUERY+='Mute:    \(.mute)\n'
  QUERY+='Status:  \(.availability)")'

  local SOURCES=$(pactl --format=json list sources | jq -cer "$QUERY" || echo "err:$?")
  
  [[ "$SOURCES" =~ ^err: ]] &&
    echo "Unable to retieve audio inputs" &&
    return 1
  
  echo "$SOURCES" | tail -n +2
}

list_playbacks () {
  local FILTER=$1

  local QUERY='.[] |'
  QUERY+='select(.properties."application.name"|test("'$FILTER'"; "i")) |'
  QUERY+='("\n'
  QUERY+='Sink:     \(.index)\n'
  QUERY+='Process:  \(.properties."application.process.id")\n'
  QUERY+='Name:     \(.properties."application.name")\n'
  QUERY+='Media:    \(.properties."media.name")\n'
  QUERY+='Mute:     \(.mute)")'

  local SINK_INPUTS=$(pactl --format=json list sink-inputs | jq -cr "$QUERY" || echo "err:$?")

  [[ "$SINK_INPUTS" =~ ^err: ]] &&
    echo "Unable to retieve audio playbacks" &&
    return 1

  [ -n "$SINK_INPUTS" ] && echo "$SINK_INPUTS" | tail -n +2 ||
    echo "No audio playbacks found"
}

set_profile () {
  local CARD=$1
  local PROFILE=$2

  if [ -z "$CARD" ]; then
    echo "Missing the card argument"
    return 1
  fi

  if [ -z "$PROFILE" ]; then
    echo "Missing the profile argument"
    return 1
  fi

  pactl set-card-profile "$CARD" "$PROFILE" && sleep 0.1 &&
    echo "Audio profile has been set to $PROFILE" ||
    echo "Unable to set the audio profile"
}

set_output () {
  local SINK=$1
  local VOLUME=$2

  if [ -z "$SINK" ]; then
    echo "Missing the output name or id argument"
    return 1
  fi

  if [ -n "$VOLUME" ]; then
    if [[ ! "$VOLUME" =~ ^[0-9]{1,3}$ ]]; then
      echo "Invalid volume argument: '$VOLUME'"
      return 1
    elif ! (($VOLUME >= 0 && $VOLUME <= 150)); then
      echo "Volume is out of the valid range: '$VOLUME'"
      return 1
    fi
  fi

  if [ -z "$VOLUME" ]; then
    pactl set-default-sink "$SINK" && sleep 0.1 &&
      echo "Default output set to $SINK" ||
      echo "Unable to set the default output"
    return 1
  fi

  if [ $VOLUME -gt 0 ]; then
    pactl set-sink-mute "$SINK" 0 &&
    pactl set-sink-volume "$SINK" "$VOLUME%" && sleep 0.1 &&
      echo "Output $SINK volume set to $VOLUME" ||
      echo "Unable to set the output volume"
  else
    pactl set-sink-mute "$SINK" 1 && sleep 0.1 &&
      echo "Output $SINK set to mute" ||
      echo "Unable to set the output to mute"
  fi
}

set_input () {
  local SOURCE=$1
  local VOLUME=$2

  if [ -z "$SOURCE" ]; then
    echo "Missing the input name or id argument"
    return 1
  fi

  if [ -n "$VOLUME" ]; then
    if [[ ! "$VOLUME" =~ ^[0-9]{1,3}$ ]]; then
      echo "Invalid volume argument: '$VOLUME'"
      return 1
    elif ! (($VOLUME >= 0 && $VOLUME <= 150)); then
      echo "Volume is out of the valid range: '$VOLUME'"
      return 1
    fi
  fi

  if [ -z "$VOLUME" ]; then
    pactl set-default-source "$SOURCE" && sleep 0.1 &&
      echo "Default input set to $SOURCE" ||
      echo "Unable to set the default input"
    return 1
  fi
  
  if [ $VOLUME -gt 0 ]; then
    pactl set-source-mute "$SOURCE" 0 &&
    pactl set-source-volume "$SOURCE" "$VOLUME%" && sleep 0.1 &&
      echo "Input $SOURCE volume set to $VOLUME" ||
      echo "Unable to set the input volume"
  else
    pactl set-source-mute "$SOURCE" 1 && sleep 0.1 &&
      echo "Input $SOURCE set to mute" ||
      echo "Unable to set input to mute"
  fi
}

set_mute () {
  local SUBJECT=$1
  local MUTE=$2

  if [ -z "$SUBJECT" ]; then
    echo "Missing the subject argument"
    return 1
  elif [[ ! "$SUBJECT" =~ ^(all|outputs|inputs)$ ]]; then
    echo "Invalid subject argument: '$SUBJECT'"
    return 1
  fi

  if [ -z "$MUTE" ]; then
    echo "Missing the mute argument"
    return 1
  elif [[ ! "$MUTE" =~ ^(1|0)$ ]]; then
    echo "Invalid mute argument: '$MUTE'"
    return 1
  fi

  if [[ "$SUBJECT" =~ (all|outputs) ]]; then
    local SINKS=$(pactl --format=json list sinks | jq -cer '.[].name' || echo "err:$?")

    [[ "$SINKS" =~ ^err: ]] &&
      echo "Unable to retieve audio outputs" &&
      return 1
    
    SINKS=($SINKS)

    local INDEX=0
    while [ $INDEX -lt ${#SINKS[@]} ]; do
      local SINK=${SINKS[INDEX]}
      pactl set-sink-mute "$SINK" "$MUTE" && sleep 0.1 &&
        echo "Output $SINK set mute to $MUTE" ||
        echo "Unable to set mute for output $SINK"
      INDEX=$((INDEX + 1))
    done
  fi

  if [[ "$SUBJECT" =~ (all|inputs) ]]; then
    local SOURCES=$(pactl --format=json list sources | jq -cer '.[].name' || echo "err:$?")

    [[ "$SOURCES" =~ ^err: ]] &&
      echo "Unable to retieve audio inputs" &&
      return 1
    
    SOURCES=($SOURCES)

    local INDEX=0
    while [ $INDEX -lt ${#SOURCES[@]} ]; do
      local SOURCE=${SOURCES[INDEX]}
      pactl set-source-mute "$SOURCE" "$MUTE" && sleep 0.1 &&
        echo "Output $SOURCE set mute to $MUTE" ||
        echo "Unable to set mute for input $SOURCE"
      INDEX=$((INDEX + 1))
    done
  fi
}

help () {
  local FRM=" %-32s\t%s\n"

  echo "Usage: COMMAND [OBJECT] [ARGUMENTS]..."

  echo -e "\nCOMMANDS"
  printf "$FRM" \
    "help" "Show this help message." \
    "show status" "Show an overall report of the system's audio." \
    "show card <name|id>" "Show data for the card with the given name or id." \
    "" "" \
    "list cards" "List all the audio cards plugged to the system." \
    "list profiles <name|id>" "List the profiles of the given audio card." \
    "list outputs" "List all output audio streams." \
    "list inputs" "List all input audio streams." \
    "list playbacks [<filter>]" "List any active audio playbacks." \
    "" "" \
    "set profile <name|id> <profile>" "Set the audio profile of the given card." \
    "set output <name|id>" "Set the default output." \
    "set output <name|id> <volume>" "Set the volume of the given output, 0 to mute." \
    "set input <name|id>" "Set the default input." \
    "set input <name|id> <volume>" "Set the volume of the given input, 0 to mute." \
    "mute all|outputs|inputs" "Mute all, output or input audio streams." \
    "unmute all|outputs|inputs" "Unmute all, output or input audio streams."

  echo -e "\nOBJECTS"
  printf "$FRM" \
    "status" "The status of the system's audio." \
    "card" "An audio card." \
    "profile" "An audio profile of a card." \
    "output" "An output audio stream (speaker)." \
    "input" "An input audio stream (microphone)." \
    "playback" "An application or process streaming audio."
}

loop () {
  clear

  while true; do
    prompt && history -s "$REPLY"

    set -f
    local OLD_IFS=$IFS && IFS=$'\n'
    local CMD=($(xargs -n1 <<< "$REPLY"))
    IFS=$OLD_IFS && set +f

    if [ "${CMD[0]}" = "help" ]; then
      help
      continue
    elif [ "${CMD[0]}" = "clear" ]; then
      clear
      continue
    elif [ "${CMD[0]}" = "quit" ]; then
      break
    elif [ -z "${CMD[0]}" ]; then
      continue
    fi

    case "${CMD[0]}" in
      "show")
        case "${CMD[1]}" in
          "status") show_status;;
          "card") show_card "${CMD[2]}";;
          *) echo "Unknown or invalid command: '$REPLY'";;
        esac;;
      "list")
        case "${CMD[1]}" in
          "cards") list_cards;;
          "profiles") list_profiles "${CMD[2]}";;
          "outputs") list_outputs;;
          "inputs") list_inputs;;
          "playbacks") list_playbacks "${CMD[2]}";;
          *) echo "Unknown or invalid command: '$REPLY'";;
        esac;;
      "set")
        case "${CMD[1]}" in
          "profile") set_profile "${CMD[2]}" "${CMD[3]}";;
          "output") set_output "${CMD[2]}" "${CMD[3]}";;
          "input") set_input "${CMD[2]}" "${CMD[3]}";;
          *) echo "Unknown or invalid command: '$REPLY'";;
        esac;;
      "mute")
        case "${CMD[1]}" in
          "all") set_mute "all" 1;;
          "outputs") set_mute "outputs" 1;;
          "inputs") set_mute "inputs" 1;;
          *) echo "Unknown or invalid command: '$REPLY'";;
        esac;;
      "unmute")
        case "${CMD[1]}" in
          "all") set_mute "all" 0;;
          "outputs") set_mute "outputs" 0;;
          "inputs") set_mute "inputs" 0;;
          *) echo "Unknown or invalid command: '$REPLY'";;
        esac;;
      *) echo "Unknown or invalid command: '$REPLY'";; 
    esac
  done

  clear
}

loop
