#!/bin/bash

set -o pipefail
source /opt/stack/utils

SETTINGS_FILE="${CONFIG_HOME}/displays.json"

require "xorg-xrandr"
require "xcalib"

# Returns a list of outputs having the given status.
# Arguments:
#  status: all, connected, disconnected,
#          active, inactive, primary
# Outputs:
#  A JSON array of outputs.
find_outputs () {
  local status="${1:-"all"}"

  local states='all|connected|disconnected|active|inactive|primary'
  if [[ ! "${status}" =~ ^(${states})$ ]]; then
    return 1
  fi

  local criteria='true'
  if [[ "${status}" == "connected" ]]; then
    criteria='.is_connected == true'
  elif [[ "${status}" == "disconnected" ]]; then
    criteria='.is_connected == false'
  elif [[ "${status}" == "active" ]]; then
    criteria='.is_connected == true and .resolution_width != null'
  elif [[ "${status}" == "inactive" ]]; then
    criteria='.is_connected == true and .resolution_width == null'
  elif [[ "${status}" == "primary" ]]; then
    criteria='.is_primary == true'
  fi

  local a=''
  a+='.screens[]|select(.screen_number==0)'
  a+=" |.associated_device|select(${criteria})"
  a="[${a}]"

  local b=''
  b+=".unassociated_devices[]|select(${criteria})"
  b="[${b}]"

  local query="[${a}+${b}|to_entries[]|{index: .key} + .value]"

  xrandr --props | jc --xrandr | jq -cer "${query}" || return 1
}

# Returns the output with the given name.
# Arguments:
#  name: any string
# Outputs:
#  A JSON object of output.
find_output () {
  local name="$1"

  local query=".[]|select(.device_name == \"${name}\")"

  find_outputs "all" | jq -cer "${query}" || return 1
}

# Returns a unique hashed signature of the current
# mapping between outputs and devices. The signature
# is a hash of the list of outputs each one is followed
# by its connected device, if any. We assume that xrandr
# works deterministically and returns the outputs always
# in the same order.
# Arguments:
#  outputs: a JSON array of outputs
# Outputs:
#  A hashed signature value.
get_sig () {
  local outputs="$1"

  local model=''
  model+='if .model_name'
  model+=' then "_\(.model_name)_\(.product_id)_\(.serial_number)"'
  model+=' else ""'
  model+='end'

  local query="[.[]|\"\(.device_name)\(${model})\"]|join(\",\")"

  local sig=''
  sig="$(echo "${outputs}" | jq -cer "${query}")" || return 1

  get_hash "${sig}" "6" || return 1
}

# Asserts if the given output is connected.
# Arguments:
#  output: a JSON object output
# Returns:
#  0 if is connected otherwise 1.
is_connected () {
  local output="${1}"

  local query='select(.is_connected)'

  echo "${output}" | jq -cer "${query}" &>/dev/null || return 1
}

# Asserts if the given output is active.
# Arguments:
#  output: a JSON object output
# Returns:
#  0 if is active otherwise 1.
is_active () {
  local output="${1}"

  local query='select(.is_connected and .resolution_width != null)'

  echo "${output}" | jq -cer "${query}" &>/dev/null || return 1
}

# Asserts if the given output is primary.
# Arguments:
#  output: a JSON object output
# Returns:
#  0 if is primary otherwise 1.
is_primary () {
  local output="${1}"

  local query='select(.is_primary)'

  echo "${output}" | jq -cer "${query}" &>/dev/null || return 1
}

# Shows a menu asking the user to select one output, where the
# answer is kept in the global var REPLY.
# Globals:
#  REPLY
# Arguments:
#  prompt:  a prompt text line
#  status: all, connected, disconnected,
#          active, inactive, primary
# Outputs:
#  A menu of output names.
pick_output () {
  local prompt="$1"
  local status="$2"

  # Convert outputs list into an array of {key, value} options
  local key='\(.device_name)'
  local value='\(.device_name) [\(if .model_name then .model_name else "NA" end)]'

  local query="[.[]|{key: \"${key}\", value: \"${value}\"}]"

  local options=''
  options="$(find_outputs "${status}" | jq -cer "${query}")" || return 1

  local len=0
  len="$(count "${options}")" || return 1
  
  if [[ ${len} -eq 0 ]]; then
    echo "No ${status:-\b} outputs have found"
    return 2
  fi

  pick_one "${prompt}" "${options}" "vertical" || return 1
}

# Shows a menu asking the user to select many outputs,
# where the answer is kept in the global var REPLY as
# a JSON array of output names.
# Globals:
#  REPLY
# Arguments:
#  prompt:  a prompt text line
#  status:  all, connected, disconnected,
#           active, inactive, primary
#  size:    the number of items must be selected
#  skip:    the output to except from selection
# Outputs:
#  A menu of output names.
pick_outputs () {
  local prompt="$1"
  local status="$2"
  local size="$3"
  local skip="$4"

  local except='select(true)'
  [[ -n "${skip}" ]] && except="select(.device_name != \"${skip}\")"

  # Convert outputs list into an array of {key, value} options
  local key='\(.device_name)'
  local value='\(.device_name) [\(if .model_name then .model_name else "NA" end)]'

  local query="{key: \"${key}\", value: \"${value}\"}"
  query="[.[]|${except}|${query}]"

  local options=''
  options="$(find_outputs "${status}" | jq -cer "${query}")" || return 1

  local len=0
  len="$(count "${options}")" || return 1

  if [[ ${len} -eq 0 ]]; then
    echo "No ${status:-\b} outputs have found"
    return 2
  fi

  pick_many "${prompt}" "${options}" "${size}" "vertical" || return 1
}

# Shows a menu of resolutions of the given output and waits
# the user to pick one option. The selected option is kept
# in the global var REPLY.
# Globals:
#  REPLY
# Arguments:
#  output: a JSON object output
# Outputs:
#  A menu of resolutions.
pick_resolution () {
  local output="$1"

  # Convert resolutions list into an array of {key, value} options
  local query=''
  query+='.associated_modes[]'
  query+=' |"\(.resolution_width)x\(.resolution_height)" as $res'
  query+=' |{key: "\($res)", value: "\($res)"}'
  query="[${query}]"

  local options=''
  options="$(echo "${output}" | jq -cer "${query}")" || return 1

  local len=0
  len="$(count "${options}")" || return 1

  if [[ ${len} -eq 0 ]]; then
    echo "No resolutions have found"
    return 2
  fi

  pick_one "Select a resolution:" "${options}" "vertical" || return 1
}

# Shows a menu of resolution rates of the given output and
# waits the user to pick one option. The selected option is
# kept in the global var REPLY.
# Globals:
#  REPLY
# Arguments:
#  output: a JSON object output
# Outputs:
#  A menu of resolution rates.
pick_rate () {
  local output="$1"
  local resolution="$2"

  # Convert rates list into an array of {key, value} options
  local query=''
  query+='.associated_modes[]'
  query+=' |"\(.resolution_width)x\(.resolution_height)" as $res'
  query+=" |select(\$res == \"${resolution}\")"
  query+=' |"\(.frequencies[].frequency)" as $freq'
  query+=' |{key: "\($freq)", value: "\($freq)"}'
  query="[${query}]"

  local options=''
  options="$(echo "${output}" | jq -cer "${query}")" || return 1

  local len=0
  len="$(count "${options}")" || return 1

  if [[ ${len} -eq 0 ]]; then
    echo "No refresh rates have found"
    return 2
  fi

  pick_one "Select a refresh rate:" "${options}" "horizontal" || return 1
}

# Shows a menu of layout modes and waits the user to pick
# one. The selected option is kept in the global var REPLY.
# Globals:
#  REPLY
# Arguments:
#  None
# Outputs:
#  A menu of layout modes.
pick_layout () {
  local len=0
  len="$(count "$(find_outputs "active")")" || return 1

  if [[ ${len} -lt 2 ]] || [[ ${len} -gt 3 ]]; then
    echo "No layouts found for ${len} display setups"
    return 2
  fi

  local layouts=''

  if [[ ${len} == 2 ]]; then
    layouts+='{"key": "row-2", "value": "SideBySide"},'
    layouts+='{"key": "col-2", "value": "TopBottom"}'
    layouts="[${layouts}]"

    echo "SideBySide  TopBottom"
    echo "----------  ----------"
    echo "[A][B]      [A]"
    echo "            [B]"
    echo
  elif [[ ${len} == 3 ]]; then
    layouts+='{"key": "row-3", "value": "SideBySide"},'
    layouts+='{"key": "col-3", "value": "TopBottom"},'
    layouts+='{"key": "gamma-3", "value": "LeftGamma"},'
    layouts+='{"key": "gamma-rev-3", "value": "RightGamma"},'
    layouts+='{"key": "lambda-3", "value": "LeftLambda"},'
    layouts+='{"key": "lambda-rev-3", "value": "RightLambda"}'
    layouts="[${layouts}]"

    echo "SideBySide  TopBottom   LeftGamma"
    echo "----------  ----------  -----------"
    echo "[A][B][C]   [A]         [A][B]"
    echo "            [B]         [C]"
    echo "            [C]"
    echo
    echo "RightGamma  LeftLambda  RightLambda"
    echo "----------  ----------  -----------"
    echo "[A][B]      [A]            [A]"
    echo "   [C]      [B][C]      [B][C]"
    echo
  fi

  pick_one "Select a layout mode:" "${layouts}" "tabular" "${len}" || return 1
}

# Shows a prompt status and asks user to enter the
# next command, which is kept in the global var REPLY.
# Globals:
#  REPLY
# Arguments:
#  None
# Outputs:
#  A minimal prompt status line.
prompt () {
  local status=''
  status="$(find_outputs "primary" | jq -cer '.[0].device_name')"
  
  if [[ $? -ne 0 ]]; then
    echo "Unable to resolve status"
    status='none'
  fi

  read -rep "[displays:${status}] " REPLY
}

# Shows the current status of Xorg and active displays.
# Globals:
#  DISPLAY, COLORS, SETTINGS_FILE
# Arguments:
#  None
# Outputs:
#  A verbose list of text data.
show_status () {
  local re='/^('
  re+='name\sof\sdisplay|'
  re+='version\snumber|'
  re+='vendor\sstring|'
  re+='vendor\srelease\snumber|'
  re+='X.Org\sversion|'
  re+='motion\sbuffer\ssize|'
  re+='image\sbyte\sorder|'
  re+='default\sscreen\snumber|'
  re+='number\sof\sscreens'
  re+=')/'

  xdpyinfo -display "${DISPLAY}" | awk -F': ' "${re}"'{
    gsub(/[ \t]+$/, "", $1);
    gsub(/^[ \t]+/, "", $2);
    printf "%-23s %s\n",$1":",$2
  }' | sed -r 's/\<./\U&/g'

  if [[ $? -ne 0 ]]; then
    echo "Unable to read xdpy info"
    return 2
  fi

  local colors='[]'
  if [[ -f "${SETTINGS_FILE}" ]]; then
    colors="$(jq -cr "if .colors then .colors else [] end" "${SETTINGS_FILE}")"
  fi

  local rate=''
  rate+='[.associated_modes[].frequencies]|flatten'
  rate+=' |[.[]|select(.is_current==true)]'
  rate+=' |.[0].frequency'

  local offset='[\(.offset_width),\(.offset_height)]'
  local trans='\(.rotation) \(.reflection|ascii_downcase)'

  # Reduce over color settings to match any devices have a profile set
  local color=''
  color+='reduce $c[] as $i ({};'
  color+='if $i.model_name == $m and $i.product_id == $p and $i.serial_number == $s'
  color+=' then . + {profile: $i.profile}'
  color+=' else . '
  color+='end)|if .profile then .profile else "none" end'

  local query=''
  query+='Output:   \(.device_name)\(if .is_primary then "*" else "" end)\n'
  query+='Device:   \(.model_name)\n'
  query+="Mode:     \(.resolution_width)x\(.resolution_height)@\(${rate})Hz\n"
  query+="Pos:      ${offset} ${trans}\n"
  query+="Color:    \(if \$c|length > 0 then (${color}) else \"none\" end)"

  local alias='.model_name as $m|.product_id as $p|.serial_number as $s'

  query=".[]|${alias}|(\"\n${query}\")"

  find_outputs "active" | jq -cer --argjson c "${colors}" "${query}"

  if [[ $? -ne 0 ]]; then
    echo "Unable to read active outputs"
    return 2
  fi
}

# Shows the Xorg displays log file.
# Globals:
#  HOME, DISPLAY
# Arguments:
#  None
# Outputs:
#  The log file of the xorg display.
show_logs () {
  local id="$(echo "${DISPLAY}" | cut -d ':' -f 2)"
  local log_file="${HOME}/.local/share/xorg/Xorg.${id}.log"

  if [[ ! -f "${log_file}" ]]; then
    echo "Unable to locate xorg log file"
    return 2
  fi

  cat "${log_file}"
}

# Shows the data of the output with the given name.
# Globals:
#  REPLY, SETTINGS_FILE
# Arguments:
#  name: any string
# Outputs:
#  A verbose list of text data.
show_output () {
  local name="$1"

  if [[ -z "${name}" ]]; then
    pick_output "Select an output:" "all" || return 1
    [[ -n "${REPLY}" ]] && name="${REPLY}" || return
  fi

  local colors='[]'
  if [[ -f "${SETTINGS_FILE}" ]]; then
    colors="$(jq -cr "if .colors then .colors else [] end" "${SETTINGS_FILE}")"
  fi

  local base=''
  base+='Name:      \(.device_name)\n'
  base+='\(if .model_name then "Device:    \(.model_name)\n" else "" end)'
  base+='Connected: \(.is_connected)\n'
  base+='Active:    \(.is_connected and .resolution_width)\n'
  base+='Primary:   \(.is_primary)'

  local rate=''
  rate+='[.associated_modes[].frequencies]|flatten'
  rate+=' |[.[]|select(.is_current==true)]'
  rate+=' |.[0].frequency'

  local extra=''
  extra+='Mode:      \(.resolution_width)x\(.resolution_height)\n'
  extra+="Rate:      \(${rate})Hz\n"
  extra+='Offset:    [\(.offset_width),\(.offset_height)]\n'
  extra+='Rotate:    \(.rotation)\n'
  extra+='Reflect:   \(.reflection|ascii_downcase)'

  # Reduce over color settings to match any devices have a profile set
  local color=''
  color+='reduce $c[] as $i ({};'
  color+='if $i.model_name == $m and $i.product_id == $p and $i.serial_number == $s'
  color+=' then . + {profile: $i.profile}'
  color+=' else . '
  color+='end)|if .profile then .profile else "none" end'

  local modes=''
  modes+='.associated_modes[]|'
  modes+='"\(.resolution_width)x\(.resolution_height)" as $mode|"'
  modes+='\($mode)'
  modes+='\($mode|if (9-length)>0 then (" "*(9-length)) else "" end)'
  modes+=' [\([.frequencies[]|.frequency]|join(", "))]"'

  modes="[${modes}]|join(\"\n           \")"

  local query=''
  query+="${base}"
  query+='\(if .is_connected and .resolution_width != null'
  query+=" then \"\n${extra}\""
  query+=' else "" end)'
  query+='\(if .is_connected'
  query+=" then \"\nColor:     \(if \$c|length > 0 then (${color}) else \"none\" end)\""
  query+=' else "" end)'
  query+='\(if .associated_modes|length != 0'
  query+=" then \"\nModes:     \(${modes})\""
  query+=' else "" end)'

  local alias='.model_name as $m|.product_id as $p|.serial_number as $s'

  query=".[]|${alias}|select(.device_name==\"${name}\")|(\"${query}\")"

  find_outputs "all" | jq -cer --argjson c "${colors}" "${query}"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find output ${name}"
    return 2
  fi
}

# Shows the list of outputs matching the given status.
# Arguments:
#  status: all, connected, disconnected,
#          active, inactive, primary
# Outputs:
#  A list of outputs.
list_outputs () {
  local status="${1:-"all"}"

  local states='all|connected|disconnected|active|inactive|primary'
  if [[ ! "${status}" =~ ^(${states})$ ]]; then
    echo "Invalid status value"
    return 2
  fi

  local query=''
  query+='Name:      \(.device_name)\n'
  query+='\(if .model_name then "Device:    \(.model_name)\n" else "" end)'
  query+='Connected: \(.is_connected)\n'
  query+='Active:    \(.is_connected and .resolution_width)\n'
  query+='Primary:   \(.is_primary)\n'

  query=".[]|(\"${query}\")"

  local outputs=''
  outputs="$(find_outputs "${status}" | jq -cr "${query}")" || return 1

  if [[ -z "${outputs}" ]]; then
    echo "No ${status:-\b} outputs have found"
    return 2
  fi

  echo "${outputs}"
}

# Sets the resolution and rate of the output with the
# given name.
# Globals:
#  REPLY
# Arguments:
#  name:       any string
#  resolution: a resolution string, e.g. 600x800
#  rate:       a decimal number, e.g. 60.00
set_mode () {
  local name="${1}"
  local resolution="${2}"
  local rate="${3}"

  if [[ -z "${name}" ]]; then
    pick_output "Select an output:" "active" || return 1
    [[ -n "${REPLY}" ]] && name="${REPLY}" || return
  fi

  local output=''
  output="$(find_output "${name}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find output ${name}"
    return 2
  elif ! is_connected "${output}"; then
    echo "Cannot set mode of a disconnected output"
    return 2
  elif ! is_active "${output}"; then
    echo "Cannot set mode of an inactive output"
    return 2
  fi

  if [[ -z "$resolution" ]]; then
    pick_resolution "${output}" || return 1
    [[ -n "${REPLY}" ]] && resolution="${REPLY}" || return
  fi
  
  if [[ ! "${resolution}" =~ ^[0-9]+x[0-9]+$ ]]; then
    echo "Invalid resolution value"
    return 2
  fi

  if [[ -z "${rate}" ]]; then
    pick_rate "${output}" "${resolution}" || return 1
    [[ -n "${REPLY}" ]] && rate="${REPLY}" || return
  fi
  
  if [[ ! "${rate}" =~ ^[0-9][0-9]+(.[0-9][0-9])?$ ]]; then
    echo "Invalid refresh rate value"
    return 2
  fi

  xrandr --output "${name}" --mode "${resolution}" --rate "${rate}"

  if [[ $? -ne 0 ]]; then
    echo "Failed to set mode of output ${name}"
    return 2
  fi

  echo "Output ${name} mode set to ${resolution}"
}

# Sets the output with the given name as primary.
# Globals:
#  REPLY
# Arguments:
#  name: any string
set_primary () {
  local name="$1"

  if [[ -z "${name}" ]]; then
    pick_output "Select an output:" "active" || return 1
    [[ -n "${REPLY}" ]] && name="${REPLY}" || return
  fi

  local output=''
  output="$(find_output "${name}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find output ${name}"
    return 2
  elif ! is_connected "${output}"; then
    echo "Cannot set primary a disconnected output"
    return 2
  elif ! is_active "${output}"; then
    echo "Cannot set primary an inactive output"
    return 2
  elif is_primary "${output}"; then
    echo "Output ${name} is already the primary"
    return 2
  fi

  xrandr --output "${name}" --primary

  if [[ $? -ne 0 ]]; then
    echo "Failed to set output ${name} as primary"
    return 2
  fi
  
  echo "Output ${name} has been set as primary"
}

# Sets the output with the given name on.
# Globals:
#  REPLY
# Arguments:
#  name: any string
set_on () {
  local name="$1"

  if [[ -z "${name}" ]]; then
    pick_output "Select an output:" "inactive" || return 1
    [[ -n "${REPLY}" ]] && name="${REPLY}" || return
  fi

  local output=''
  output="$(find_output "${name}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find output ${name}"
    return 2
  elif ! is_connected "${output}"; then
    echo "Cannot activate a disconnected output"
    return 2
  elif is_active "${output}"; then
    echo "Output ${name} is already active"
    return 2
  fi

  xrandr --output "${name}" --auto

  if [[ $? -ne 0 ]]; then
    echo "Failed to activate output ${name}"
    return 2
  fi
  
  echo "Output ${name} has been activated"
}

# Sets the output with the given name off.
# Globals:
#  REPLY
# Arguments:
#  name: any string
set_off () {
  local name="$1"

  if [[ -z "${name}" ]]; then
    pick_output "Select an output:" "active" || return 1
    [[ -n "${REPLY}" ]] && name="${REPLY}" || return
  fi

  local output=''
  output="$(find_output "${name}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find output ${name}"
    return 2
  elif ! is_connected "${output}"; then
    echo "Cannot deactivate a disconnected output"
    return 2
  elif ! is_active "${output}"; then
    echo "Output ${output} is already inactive"
    return 2
  elif is_primary "${output}"; then
    echo "Cannot deactivate the primary output"
    return 2
  fi

  xrandr --output "${name}" --off

  if [[ $? -ne 0 ]]; then
    echo "Failed to deactivate output ${name}"
    return 2
  fi
  
  echo "Output ${name} has been deactivated"
}

# Sets the reflection of the output with the given name.
# Globals:
#  REPLY
# Arguments:
#  name: any string
#  mode: normal, x, y, xy
reflect () {
  local name="$1"
  local mode="$2"
  
  if [[ -z "${name}" ]]; then
    pick_output "Select an output:" "active" || return 1
    [[ -n "${REPLY}" ]] && name="${REPLY}" || return
  fi

  local output=''
  output="$(find_output "${name}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find output ${name}"
    return 2
  elif ! is_connected "${output}"; then
    echo "Cannot reflect a disconnected output"
    return 2
  elif ! is_active "${output}"; then
    echo "Cannot reflect an inactive output"
    return 2
  fi

  if [[ -z "${mode}" ]]; then
    local modes=''
    modes+='{"key": "normal", "value": "Normal"},'
    modes+='{"key": "x", "value": "X Axis"},'
    modes+='{"key": "y", "value": "Y Axis"},'
    modes+='{"key": "xy", "value": "XY Axis"}'
    modes="[${modes}]"

    pick_one "Select a reflection mode:" "${modes}" "horizontal" || return 1
    [[ -n "${REPLY}" ]] && mode="${REPLY}" || return
  fi
  
  if [[ ! "${mode}" =~ ^(normal|x|y|xy)$ ]]; then
    echo "Invalid reflection value"
    return 2
  fi

  xrandr --output "${name}" --reflect "${mode}"
    
  if [[ $? -ne 0 ]]; then
    echo "Failed to reflect output ${name}"
    return 2
  fi

  echo "Output ${name} reflected to ${mode} mode"
}

# Sets the rotation of the output with the given name.
# Globals:
#  REPLY
# Arguments:
#  name: any string
#  mode: normal, right, left, inverted
rotate () {
  local name="$1"
  local mode="$2"

  if [[ -z "${name}" ]]; then
    pick_output "Select an output:" "active" || return 1
    [[ -n "${REPLY}" ]] && name="${REPLY}" || return
  fi

  local output=''
  output="$(find_output "${name}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find output ${name}"
    return 2
  elif ! is_connected "${output}"; then
    echo "Cannot rotate a disconnected output"
    return 2
  elif ! is_active "${output}"; then
    echo "Cannot rotate an inactive output"
    return 2
  fi

  if [[ -z "${mode}" ]]; then
    local modes=''
    modes+='{"key": "normal", "value": "Normal"},'
    modes+='{"key": "right", "value": "Right"},'
    modes+='{"key": "left", "value": "Left"},'
    modes+='{"key": "inverted", "value": "Inverted"}'
    modes="[${modes}]"

    pick_one "Select a rotation mode:" "${modes}" "horizontal" || return 1
    [[ -n "${REPLY}" ]] && mode="${REPLY}" || return
  fi
  
  if [[ ! "${mode}" =~ ^(normal|right|left|inverted)$ ]]; then
    echo "Invalid rotation value"
    return 2
  fi

  xrandr --output "${name}" --rotate "${mode}"
    
  if [[ $? -ne 0 ]]; then
    echo "Failed to rotate output ${name}"
    return 2
  fi
  
  echo "Output ${name} rotated to ${mode} mode"
}

# Mirrors the output with the given name to other outputs,
# having all mirrors run at a common resolution shared among
# the source output and the mirrors. All outputs will move to
# position equal to the position of the source output and
# inherit the rotation and reflection modes.
# Globals:
#  REPLY
# Arguments:
#  name: any string
mirror () {
  local name="$1"

  if [[ -z "${name}" ]]; then
    pick_output "Select an output:" "active" || return 1
    [[ -n "${REPLY}" ]] && name="${REPLY}" || return
  fi

  local output=''
  output="$(find_output "${name}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find output ${name}"
    return 2
  elif ! is_connected "${output}"; then
    echo "Cannot mirror a disconnected output"
    return 2
  elif ! is_active "${output}"; then
    echo "Cannot mirror an inactive output"
    return 2
  fi

  local outputs=''
  outputs="$(find_outputs "active")" || return 1

  local len=0
  len="$(count "${outputs}")" || return 1

  if [[ ${len} -lt 2 ]]; then
    echo "No other outputs have found to mirror"
    return 2
  fi

  local mirrors=''
  pick_outputs "Select on which outputs to mirror:" "active" "1," "${name}" || return 1
  [[ -n "${REPLY}" ]] && mirrors="${REPLY}" || return

  # Find the common resolution modes among output and mirrors
  local names=''
  names="$(echo "${mirrors}" | jq -cer '.|join("|")')" || return 1
  names+="|${name}"

  local query=''
  query+="select(.device_name | match(\"(${names})\"))"
  query+=' |.associated_modes[]'
  query+=' |"\(.resolution_width)x\(.resolution_height)"'

  query="[.[]|${query}]"
  query+=' |[group_by(.)|map(select(length>1))|.[]|.[0]'
  query+=' |{key: "\(.)", value: "\(.)"}]'

  local modes=''
  modes="$(echo "${outputs}" | jq -cer "${query}")" || return 1

  if [[ "$(count "${modes}")" -eq 0 ]]; then
    echo "Mirrors do not share common resolutions"
    return 2
  fi

  local mode=''
  pick_one "Select the mirroring resolution:" "${modes}" "vertical" || return 1
  [[ -n "${REPLY}" ]] && mode="${REPLY}" || return

  # Have mirrors inherit the position and rotate/reflect of the source output
  local pos="$(echo "${output}" | jq -r '"\(.offset_width)x\(.offset_height)"')"
  local rot="$(echo "${output}" | jq -r '.rotation')"
  local ref="$(echo "${output}" | jq -r '.reflection|ascii_downcase' |
    awk '{gsub(/( |and|axis)/,"",$0); print}')"

  query="[\"--output \(.[]) --mode ${mode} --pos ${pos} --rotate ${rot} --reflect ${ref}\"]"
  query+='|join(" ")'

  local others=''
  others="$(echo "${mirrors}" | jq -cr "${query}")" || return 1

  xrandr --output "${name}" --mode "${mode}" ${others}

  if [[ $? -ne 0 ]]; then
    echo "Failed to mirror output ${name}"
    return 2
  fi
  
  echo "Output ${name} mirrored successfully"
}

# Sets the layout of currently active outputs.
# Globals:
#  REPLY
# Arguments:
#  None
set_layout () {
  local layout=''
  pick_layout || return 1
  [[ -n "$REPLY" ]] && layout="${REPLY}" || return

  local outputs=''
  pick_outputs "Pick outputs by order:" "active" "all" || return 1
  [[ -n "$REPLY" ]] && outputs="${REPLY}" || return

  local a="$(echo "${outputs}" | jq -cr '.[0]')"
  local b="$(echo "${outputs}" | jq -cr '.[1]')"
  local c="$(echo "${outputs}" | jq -cr '.[2]')"

  local args=''
  case "${layout}" in
    "row-2")
      args="--output ${a} --left-of ${b}";;
    "col-2")
      args="--output ${a} --above ${b}";;
    "row-3")
      args="--output ${a} --left-of ${b} --output ${b} --left-of ${c}";;
    "col-3")
      args="--output ${a} --above ${b} --output ${b} --above ${c}";;
    "gamma-3")
      args="--output ${a} --left-of ${b} --output ${c} --below ${a}";;
    "gamma-rev-3")
      args="--output ${a} --left-of ${b} --output ${c} --below ${b}";;
    "lambda-3")
      args="--output ${a} --above ${b} --output ${b} --left-of ${c}";;
    "lambda-rev-3")
      args="--output ${a} --left-of ${c} --output ${a} --above ${c}";;
    *)
      echo "Invalid layout mode"
      return 2;;
  esac

  xrandr ${args}

  if [[ $? -ne 0 ]]; then
    echo "Failed to set layout mode"
    return 2
  fi

  echo "Layout has been set successfully"
}

# Saves the current layout under a unique hashed signature
# which is based on the mapping between outputs and devices.
# Globals:
#  REPLY, CONFIG_HOME, SETTINGS_FILE
# Arguments:
#  None
save_layout () {
  local outputs=''
  outputs="$(find_outputs "all")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to read outputs"
    return 2
  fi

  # Parse each output to an object with device and xrandr mode options
  local device=''
  device+='if .model_name'
  device+=' then "\(.model_name)_\(.product_id)_\(.serial_number)"'
  device+=' else "NA"'
  device+='end'

  local res=''
  res+='.associated_modes[]'
  res+=' |"\(.resolution_width)x\(.resolution_height)" as $res'
  res+=' |.frequencies[]|select(.is_current)'
  res+=' |"--mode \($res) --rate \(.frequency)"'

  local pos='--pos \(.offset_width)x\(.offset_height)'
  local rotate='--rotate \(.rotation)'
  local reflect='--reflect \(.reflection|ascii_downcase|gsub("( |and|axis)";""))'
  local primary='if .is_primary then " --primary" else "" end'

  local mode=''
  mode+='if .resolution_width'
  mode+=" then \"\(${res}) ${pos} ${rotate} ${reflect}\(${primary})\""
  mode+=' else "--off"'
  mode+='end'

  local query="{\"device\": \"\(${device})\", \"mode\": \"\(${mode})\"}"
  query="map({(.device_name|tostring): ${query}})|add"

  local map=''
  map="$(echo "${outputs}" | jq -cer "${query}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to parse the layout mapping"
    return 2
  fi

  # Assign a signature to the current layout mapping
  local sig="$(get_sig "${outputs}")" || return 1
  local layout="{\"sig\": \"${sig}\", \"map\": ${map}}"

  local settings='{}'

  if [[ -f "${SETTINGS_FILE}" ]]; then
    local layouts=''
    layouts="$(jq '.layouts' "${SETTINGS_FILE}" 2>/dev/null)"

    if [[ $? -ne 0 ]]; then
      echo "Unable to read the layout settings"
      return 2
    fi

    if [[ "${layouts}" != "null" ]]; then
      local exists=''
      exists="$(jq ".layouts[]|select(.sig == \"${sig}\")" "${SETTINGS_FILE}" 2>/dev/null)"

      if [[ $? -ne 0 ]]; then
        echo "Failed to read the layout settings"
        return 2
      fi

      if [[ -n "${exists}" ]]; then
        settings="$(jq -e "(.layouts[]|select(.sig == \"${sig}\")|.map)|= ${map}" "${SETTINGS_FILE}")"
      else
        settings="$(jq -e ".layouts += [${layout}] " "${SETTINGS_FILE}")"
      fi
    else
      settings="$(jq -e ".layouts = [${layout}] " "${SETTINGS_FILE}")"
    fi
  else
    settings="$(echo "{\"layouts\": [${layout}]}" | jq -e '.')"
  fi

  if [[ $? -ne 0 ]]; then
    echo "Failed to parse the layout settings"
    return 2
  fi

  mkdir -p "${CONFIG_HOME}"
  echo "${settings}" > "${SETTINGS_FILE}"

  if [[ $? -ne 0 ]]; then
    echo "Failed to save the layout settings"
    return 2
  fi
  
  echo "Layout has been saved successfully"
}

# Restores the layout with the signature matching the
# signature of the current mapping between outputs and
# devices.
# Globals:
#  SETTINGS_FILE
# Arguments:
#  None
restore_layout () {
  if [[ ! -f "${SETTINGS_FILE}" ]]; then
    echo "No layout settings have found"
    return
  fi

  local layouts=''
  layouts="$(jq ".layouts" "${SETTINGS_FILE}" 2>/dev/null)"

  if [[ $? -ne 0 ]]; then
    echo "Unable to read layout settings"
    return 2
  elif [[ "${layouts}" == "null" ]]; then
    echo "No layout settings have found"
    return
  fi

  local outputs=''
  outputs="$(find_outputs "all")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to read outputs"
    return 2
  fi

  # Calculate the hashed signature of the current mapping
  local sig="$(get_sig "${outputs}")" || return 1

  # Collect all output xrandr mode options matching the sig
  local query='"--output \(.key) \(.value.mode)"'
  query="[.layouts[]|select(.sig == \"${sig}\")|.map|to_entries[]|${query}]|join(\" \")"

  local args=''
  args="$(jq -cer "${query}" "${SETTINGS_FILE}" 2>/dev/null)"

  if [[ $? -ne 0 ]]; then
    echo "Unable to read layout settings"
    return 2
  elif [[ -z "${args}" ]]; then
    echo "No layout found for the current setup"
    return 2
  fi

  xrandr ${args}

  if [[ $? -ne 0 ]]; then
    echo "Failed to restore the layout"
    return 2
  fi

  echo "Layout has been restored"
}

# Delete the layout with the given signature.
# Globals:
#  REPLY, SETTINGS_FILE
# Arguments;
#  sig: the signature of a layout
delete_layout () {
  local sig="$1"

  if [[ ! -f "${SETTINGS_FILE}" ]]; then
    echo "No layout settings have found"
    return 2
  fi

  local layouts=''
  layouts="$(jq '.layouts' "${SETTINGS_FILE}" 2>/dev/null)"

  if [[ $? -ne 0 ]]; then
    echo "Unable to read layout settings"
    return 2
  elif [[ "${layouts}" == "null" ]]; then
    echo "No layout settings have found"
    return 2
  fi

  if [[ -z "${sig}" ]]; then
    local sigs=''
    sigs="$(jq -cr '[.layouts[]|{key: .sig, value: .sig}]' "${SETTINGS_FILE}" 2>/dev/null)"

    if [[ $? -ne 0 ]] || [[ -z "${sigs}" ]]; then
      echo "Unable to read layout settings"
      return 2
    elif [[ "${sigs}" == "[]" ]]; then
      echo "No layout settings have found"
      return 2
    fi

    # Show a help report of layout mappings per signature
    local query="\(.sig)\n \([.map|to_entries[]|\"\(.key) [\(.value.device)]\"]|join(\"\n \"))"
    query="[.layouts[]|\"${query}\"]|join(\"\n\n\")"

    jq -r "${query}" "${SETTINGS_FILE}"

    pick_one "Select a layout:" "${sigs}" "vertical" || return 1
    [[ -n "${REPLY}" ]] && sig="${REPLY}" || return
  fi

  local exists=''
  exists="$(jq -e ".layouts[]|select(.sig == \"${sig}\")" "${SETTINGS_FILE}")"

  if [[ $? -ne 0 ]]; then
    echo "Cannot find layout ${sig}"
    return 2
  fi

  local settings=''
  settings="$(jq -e "del(.layouts[]|select(.sig == \"${sig}\"))" "${SETTINGS_FILE}")"

  if [[ $? -ne 0 ]]; then
    echo "Failed to delete layout ${sig}"
    return 2
  fi

  echo "${settings}" > "${SETTINGS_FILE}"

  if [[ $? -ne 0 ]]; then
    echo "Failed to update layout settings"
    return 2
  fi
  
  echo "Layout ${sig} has been deleted"
}

# Sets the color profile of the device connected to the output
# with the given name and save it to the color settings. The
# profile should be the filename of any .icc or .icm color
# calibration files stored in $COLORS_HOME.
# Globals:
#  REPLY, COLORS_HOME, DISPLAY, CONFIG_HOME, SETTINGS_FILE
# Arguments:
#  name:    the name of an output
#  profile: the file name of a color profile
set_color () {
  local name="$1"
  local profile="$2"

  if [[ -z "${name}" ]]; then
    pick_output "Select an output:" "active" || return 1
    [[ -n "${REPLY}" ]] && name="${REPLY}" || return
  fi
  
  local output=''
  output="$(find_output "${name}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find output ${name}"
    return 2
  elif ! is_connected "${output}"; then
    echo "Cannot set color of a disconnected output"
    return 2
  elif ! is_active "${output}"; then
    echo "Cannot set color of an inactive output"
    return 2
  fi

  if [[ -z "${profile}" ]]; then
    local query='{key: .filename, value: .filename}'
    query="[.[]|select(.filename|test(\".ic(c|m)$\"))|${query}]"
  
    local profiles=''
    profiles="$(ls "${COLORS_HOME}" 2>/dev/null | jc --ls | jq -cer "${query}")"
    
    local len=0
    len="$(count "${profiles}")" || return 1

    if [[ ${len} -eq 0 ]]; then
      echo "No color profiles have found"
      return 2
    fi

    pick_one "Select a color profile:" "${profiles}" "vertical" || return 1
    [[ -n "${REPLY}" ]] && profile="${REPLY}" || return
  fi

  if [[ ! -f "${COLORS_HOME}/${profile}" ]]; then
    echo "Cannot find color profile file"
    return 2
  fi

  local index=''
  index="$(get "${output}" ".index")" || return 1

  local result=''
  result="$(xcalib -d "${DISPLAY}" -s 0 -o "${index}" "${COLORS_HOME}/${profile}" 2>&1)"

  if [[ $? -ne 0 ]] || [[ -n "${result}" ]]; then
    echo "Failed to set color profile"
    return 2
  fi

  echo "Color profile has been set"

  # Save color profile to color settings
  local query=''
  query+='model_name: .model_name,'
  query+='product_id: .product_id,'
  query+='serial_number: .serial_number,'
  query+="profile: \"${profile}\""
  query="{${query}}"

  local color=''
  color="$(echo "${output}" | jq -cr "${query}")"

  local settings='{}'

  if [[ -f "${SETTINGS_FILE}" ]]; then
    local colors=''
    colors="$(jq 'if .colors then .colors else empty end' "${SETTINGS_FILE}")"

    if [[ -n "${colors}" ]]; then
      local query=''
      query+='.model_name == $c.model_name and '
      query+='.product_id == $c.product_id and '
      query+='.serial_number == $c.serial_number'
      query=".colors[]|select(${query})"

      local exists=''
      exists="$(jq --argjson c "${color}" "${query}" "${SETTINGS_FILE}")"

      if [[ -n "${exists}" ]]; then
        query="(${query}|.profile)|=\"${profile}\""
      else
        query=".colors += [${color}]"
      fi

      settings="$(jq --argjson c "${color}" "${query}" "${SETTINGS_FILE}")"
    else
      settings="$(jq ".colors = [${color}]" "${SETTINGS_FILE}")"
    fi
  else
    settings="$(echo "{\"colors\": [${color}]}" | jq '.')"
  fi

  mkdir -p "${CONFIG_HOME}"
  echo "${settings}" > "${SETTINGS_FILE}"
}

# Resets the color profile of the device connected to the
# output with the given name and removes it from the color
# settings.
# Globals:
#  REPLY, DISPLAY, SETTINGS_FILE
# Arguments:
#  name: the name of an output
reset_color () {
  local name="$1"

  if [[ -z "${name}" ]]; then
    pick_output "Select an output:" "active" || return 1
    [[ -n "${REPLY}" ]] && name="${REPLY}" || return
  fi

  local output=''
  output="$(find_output "${name}")"

  if [[ $? -ne 0 ]]; then
    echo "Unable to find output ${name}"
    return 2
  elif ! is_connected "${output}"; then
    echo "Cannot reset color of a disconnected output"
    return 2
  elif ! is_active "${output}"; then
    echo "Cannot reset color of an inactive output"
    return 2
  fi

  local index=''
  index="$(get "${output}" ".index")" || return 1

  local result=''
  result="$(xcalib -d "${DISPLAY}" -s 0 -o "${index}" -c 2>&1)"

  if [[ $? -ne 0 ]] || [[ -n "${result}" ]]; then
    echo "Failed to reset color profile"
    return 2
  fi

  echo "Color profile has been reset"

  # Try to remove color profile from color settings
  if [[ ! -f "${SETTINGS_FILE}" ]]; then
    return
  fi

  local query=''
  query+='.model_name == $o.model_name and '
  query+='.product_id == $o.product_id and '
  query+='.serial_number == $o.serial_number'
  query="if .colors then .colors[]|select(${query}) else empty end"

  local settings=''
  settings="$(jq --argjson o "${output}" "del(${query})" "${SETTINGS_FILE}")"

  echo "${settings}" > "${SETTINGS_FILE}"
}

# Deletes the color setting with the given index.
# Globals:
#  SETTINGS_FILE, REPLY
# Arguments:
#  index: the index of a color setting
delete_color () {
  local index="$1"

  if [[ ! -f "${SETTINGS_FILE}" ]]; then
    echo "No colors settings have found"
    return 2
  fi

  if [[ -z "${index}" ]]; then
    local query=''
    query+='{key: .key, value: "\(.key):\(.value.model_name) [\(.value.profile)]"}'
    query="if .colors|length > 0 then [.colors|to_entries[]|${query}] else [] end"

    local colors=''
    colors="$(jq -cer "${query}" "${SETTINGS_FILE}")" || return 1
    
    local len=0
    len="$(count "${colors}")" || return 1

    if [[ ${len} -eq 0 ]]; then
      echo "No colors settings have found"
      return 2
    fi

    pick_one "Select a color setting:" "${colors}" "tabular" || return 1
    [[ -n "${REPLY}" ]] && index="${REPLY}" || return
  fi

  local exists=''
  exists="$(jq "select(.colors[${index}])" "${SETTINGS_FILE}")"

  if [[ -z "${exists}" ]]; then
    echo "Cannot find color setting"
    return 2
  fi

  local settings='{}'
  settings="$(jq -e "del(.colors|.[${index}])" "${SETTINGS_FILE}")"

  if [[ $? -ne 0 ]]; then
    echo "Failed to delete color setting"
    return 2
  fi

  echo "${settings}" > "${SETTINGS_FILE}"

  echo "Color setting has been deleted"
}

# List all the colors per device have stored in settings.
# Globals:
#  SETTINGS_FILE
# Arguments:
#  none
list_colors () {
  if [[ ! -f "${SETTINGS_FILE}" ]]; then
    echo "No colors have found"
    return
  fi

  local color=''
  color+='Index:   \(.key)\n'
  color+='Device:  \(.value.model_name)\n'
  color+='Product: \(.value.product_id)\n'
  color+='Serial:  \(.value.serial_number)\n'
  color+='Profile: \(.value.profile)'

  local query=''
  query+='if .colors|length > 0'
  query+=" then .colors|to_entries[]|\"${color}\""
  query+=' else "No colors have found"'
  query+='end'

  query="[${query}]|join(\"\n\n\")"

  jq -cer "${query}" "${SETTINGS_FILE}"

  if [[ $? -ne 0 ]]; then
    echo "Unable to list colors"
    return 2
  fi
}

# Restores the color profiles of any devices currently
# connected to an output, only if such profile is stored
# in the settings file.
# Globals:
#  COLORS_HOME, SETTINGS_FILE, DISPLAY
# Arguments:
#  None
restore_colors () {
  if [[ ! -f "${SETTINGS_FILE}" ]]; then
    echo "No color settings have found"
    return
  fi

  local colors=''
  colors="$(jq -cr 'if .colors then .colors else [] end' "${SETTINGS_FILE}")"

  local len=0
  len="$(count "${colors}")" || return 1

  if [[ ${len} -eq 0 ]]; then
    echo "No color settings have found"
    return
  fi

  local outputs=''
  outputs="$(find_outputs "active")" || return 1

  local query=''
  query+='. + $c'
  query+=' |group_by([.model_name, .product_id, .serial_number])'
  query+=" |map({index: (.[0].index), profile: (.[].profile|select(.))})[]"
  query+=" |\"xcalib -d ${DISPLAY} -s 0 -o \(.index) ${COLORS_HOME}/\(.profile)\""

  local xcalib_cmds=''
  xcalib_cmds="$(echo "${outputs}" | jq -cr --argjson c "${colors}" "${query}")" || return 1

  # Iterate over xcalib commands and execute
  local failed='false'
  local xcalib_cmd=''
  while read -r xcalib_cmd; do
    local result="$(${xcalib_cmd} 2>&1)"

    if [[ $? -ne 0 ]] || [[ -n "${result}" ]]; then
      failed='true'
    fi
  done <<< "${xcalib_cmds}"

  if [[ "${failed}" == "true" ]]; then
    echo "Failed to restore all color profiles"
    return 2
  fi

  echo "Color profiles have been restored"
}

# Show the help message.
# Globals:
#  COLORS_HOME
# Arguments:
#  None
# Outputs:
#  A long help message.
help () {
  if [[ "$1" == "once" ]]; then
    echo "Usage: displays COMMAND [OBJECT] [ARGUMENTS]..."

    echo -e "\nCOMMANDS"
    printf " %-16s %s\n" \
      "help" "Show this help message." \
      "" "" \
      "restore layout" "Restore the layout." \
      "restore colors" "Restore color profiles."

    return
  fi

  echo "Usage: COMMAND [OBJECT] [ARGUMENTS]..."

  echo -e "\nCOMMANDS"
  printf " %-44s %s\n" \
    "help" "Show this help message." \
    "" "" \
    "show status" "Show a report of the Xorg server and active outputs." \
    "show logs" "Show the logs of the Xorg server." \
    "show output [<name>]" "Show the data of the given output." \
    "" "" \
    "list outputs [<status>]" "List all outputs or by the given status," \
    "" "all, connected, disconnected, active, inactive or primary." \
    "" "" \
    "set mode [<output> [<resolution> [<rate>]]]" "Set the mode of the given output." \
    "set primary [<output>]" "Set the given output as primary." \
    "set on|off [<output>]" "Set active or inactive the given output." \
    "" "" \
    "rotate [<output> [<mode>]]" "Set output rotation to normal, right, left or inverted." \
    "reflect [<output> [<mode>]]" "Set output reflection to normal, x, y or xy axes." \
    "mirror [<output>]" "Mirror the given active output to other outputs." \
    "" "" \
    "set color [<output> [<profile>]]" "Set color profile of the device connected to output," \
    "" "where profile should be any calibration files" \
    "" "stored under ${COLORS_HOME}." \
    "reset color [<output>]" "Reset color profile of the device connected to output." \
    "delete color [<index>]" "Delete the color setting with the given index." \
    "list colors" "List any colors have set per device." \
    "restore colors" "Restore color profiles saved in settings." \
    "" "" \
    "set layout" "Set the layout of active outputs." \
    "save layout" "Save the current layout." \
    "delete layout [<sig>]" "Delete the layout with the given signature." \
    "restore layout" "Restore the layout saved in settings."
}

loop () {
  clear

  while true; do
    prompt && history -s "${REPLY}"

    set -f
    set_separator "line"
    local cmd=($(xargs -n1 <<< "${REPLY}"))
    restore_separator && set +f

    if [[ "${cmd[0]}" == "help" ]]; then
      help
      continue
    elif [[ "${cmd[0]}" == "clear" ]]; then
      clear
      continue
    elif [[ "${cmd[0]}" == "quit" ]]; then
      break
    elif [[ -z "${cmd[0]}" ]]; then
      continue
    fi

    case "${cmd[0]}" in
      "show")
        case "${cmd[1]}" in
          "status") show_status;;
          "logs") show_logs;;
          "output") show_output "${cmd[2]}";;
          *) echo "Invalid or unknown command";;
        esac;;
      "list")
        case "${cmd[1]}" in
          "outputs") list_outputs "${cmd[2]}";;
          "colors") list_colors;;
          *) echo "Invalid or unknown command";;
        esac;;
      "set")
        case "${cmd[1]}" in
          "layout") set_layout;;
          "mode") set_mode "${cmd[2]}" "${cmd[3]}" "${cmd[4]}";;
          "primary") set_primary "${cmd[2]}";;
          "on") set_on "${cmd[2]}";;
          "off") set_off "${cmd[2]}";;
          "color") set_color "${cmd[2]}" "${cmd[3]}";;
          *) echo "Invalid or unknown command";;
        esac;;
      "reset")
        case "${cmd[1]}" in
          "color") reset_color "${cmd[2]}";;
          *) echo "Invalid or unknown command";;
        esac;;
      "save")
        case "${cmd[1]}" in
          "layout") save_layout;;
          *) echo "Invalid or unknown command";;
        esac;;
      "delete")
        case "${cmd[1]}" in
          "layout") delete_layout "${cmd[2]}";;
          "color") delete_color "${cmd[2]}";;
          *) echo "Invalid or unknown command";;
        esac;;
      "restore")
        case "${cmd[1]}" in
          "layout") restore_layout;;
          "colors") restore_colors;;
          *) echo "Invalid or unknown command";;
        esac;;
      "rotate") rotate "${cmd[1]}" "${cmd[2]}";;
      "reflect") reflect "${cmd[1]}" "${cmd[2]}";;
      "mirror") mirror "${cmd[1]}";;
      *) echo "Invalid or unknown command";;
    esac

    if [[ $? -eq 1 ]]; then
      echo "An unknown error has occurred"
    fi
  done

  clear
}

once () {
  case "$1" in
    "help") help "once";;
    "restore")
      case "$2" in
        "layout") restore_layout;;
        "colors") restore_colors;;
        *) abort "Invalid or unknown command";;
      esac;;
    *) abort "Invalid or unknown command";;
  esac

  if [[ $? -ne 0 ]]; then
    abort
  fi
}

if [[ $# -eq 0 ]]; then
  loop
else
  once "$@"
fi