#!/usr/bin/env bash

source ~/.config/stack/utils

require "bspwm"

if [ "$1" = "-y" ]; then
  REPLY="yes"
else
  askme "The user will be logged out, proceed?" "yes" "no"
fi

if [ "$REPLY" = "yes" ]; then
  bspc quit
fi
