#!/usr/bin/env bash

help () {
  echo "Usage: notifications COMMAND [ARGUMENTS]..."

  echo -e "\nCOMMANDS"
  printf " %-45s\t%s\n" \
    "help" "Show this message" \
    "" "" \
    "push <title> <message>" "Show a notification."
}

push () {
  local TITLE=$1
  local MESSAGE=$2

  notify-send -t 5000 "$TITLE" "$MESSAGE"
}

case "$1" in
  "help") help;;
  "push") push "$2" "$3";;
  *) echo "Invalid or unknown command";; 
esac