#!/usr/bin/env bash

source ~/.config/stack/utils

if [ "$1" = "-y" ]; then
  REPLY="yes"
else
  askme "The system will be shutdown, proceed?" "yes" "no"
fi

if [ "$REPLY" = "yes" ]; then
  shutdown now
fi
