#!/usr/bin/env bash

set -o pipefail
source /opt/stack/utils

CONFIG_HOME="$HOME/.config/stack/theme"
WALLPAPERS_HOME="$CONFIG_HOME/wallpapers"
WALLPAPER_CONFIG="$CONFIG_HOME/wallpaper"

require "feh"

prompt () {
  read -rep "[theme:${YE}ready$RS] " REPLY
}

set_wallpaper () {
  local IMAGE=$1

  local TYPES='jpg|jpeg|png'

  if [ -z "$IMAGE" ]; then
    local IMAGES="$(ls -1 "$WALLPAPERS_HOME" | awk '{ORS="'$AES'";} /.+\.('$TYPES')$/{print}')"
    local LEN=$(count "$IMAGES")

    if [ $LEN = 0 ]; then
      echo "No wallpaper images have found"
      return
    fi

    pick_one "Select an image file:" "$IMAGES" "vertical-6" || return 1
    [ -z "$REPLY" ] && return

    IMAGE="$WALLPAPERS_HOME/$(value "$REPLY")"
  fi

  if [[ ! "$IMAGE" =~ ^/ ]]; then
    echo "File path should be an absolute path"
    return 1
  elif [ ! -f "$IMAGE" ]; then
    echo "Invalid or unknown file path"
    return 1
  elif [[ ! "$IMAGE" =~ .+\.($TYPES)$ ]]; then
    echo "Only jpeg or png files are supported"
    return 1
  fi

  local IMAGE_NAME="$(basename "$IMAGE")"

  if [ ! "$IMAGE" = "$WALLPAPERS_HOME/$IMAGE_NAME" ]; then
    while [ -f "$WALLPAPERS_HOME/$IMAGE_NAME" ]; do
      IMAGE_NAME="copy_${IMAGE_NAME}"
    done

    cp "$IMAGE" "$WALLPAPERS_HOME/$IMAGE_NAME"
    IMAGE="$WALLPAPERS_HOME/$IMAGE_NAME"
  fi

  printf "file=$IMAGE" > "$WALLPAPER_CONFIG"

  load_wallpaper
}

load_wallpaper () {
  if [ ! -f "$WALLPAPER_CONFIG" ]; then
    echo "No wallpaper config file found"
    return 1
  fi

  local FILE="$(cat "$WALLPAPER_CONFIG" | awk -F'=' '/^file=/{print $2}')"

  feh --no-fehbg --bg-fill "$FILE"

  if [ ! $? -eq 0 ]; then
    echo "Failed to load the wallpaper"
    return 1
  fi

  echo "Wallpaper has been loaded"
}

help () {
  if [ "$1" = "once" ]; then
    echo "Usage: theme COMMAND [OBJECT] [ARGUMENTS]..."

    echo -e "\nCOMMANDS"
    printf " %-16s %s\n" \
      "help" "Show this help message." \
      "" "" \
      "load wallpaper" "Load the desktop wallpaper."

    return
  fi

  echo "Usage: COMMAND [OBJECT] [ARGUMENTS]..."

  echo -e "\nCOMMANDS"
  printf " %-25s %s\n" \
    "help" "Show this help message." \
    "" "" \
    "set wallpaper [<image>]" "Set the desktop wallpaper to the given image file."
}

loop () {
  clear

  while true; do
    prompt && history -s "$REPLY"

    set -f
    set_separator "line"
    local CMD=($(xargs -n1 <<< "$REPLY"))
    restore_separator && set +f

    if [ "${CMD[0]}" = "help" ]; then
      help
      continue
    elif [ "${CMD[0]}" = "clear" ]; then
      clear
      continue
    elif [ "${CMD[0]}" = "quit" ]; then
      break
    elif [ -z "${CMD[0]}" ]; then
      continue
    fi

    case "${CMD[0]}" in
      "set")
        case "${CMD[1]}" in
          "wallpaper") set_wallpaper "${CMD[2]}";;
          *) echo "Unknown or invalid command";;
        esac;;
      *) echo "Unknown or invalid command";; 
    esac
  done

  clear
}

once () {
  case "$1" in
    "help") help once;;
    "load")
      case "$2" in
        "wallpaper") load_wallpaper || abort;;
        *) abort "Invalid or unknown command";;
      esac;;
    *) abort "Invalid or unknown command";;
  esac
}

if [ $# = 0 ]; then
  loop
else
  once "$@"
fi