#!/usr/bin/env bash

set -o pipefail
source /opt/stack/utils

WALLPAPERS_HOME=$HOME/images/wallpapers
SETTINGS=$HOME/.config/gtk-3.0/settings.ini

require "feh"

prompt () {
  local THEME="$(cat "$SETTINGS" | awk -F'=' '/gtk-theme-name/{print $2}')"
  
  local STATUS="default"
  [ -n "$THEME" ] && STATUS="${THEME,,}"

  read -rep "[theme:$YE${STATUS}$RS] " REPLY
}

show_status () {
  cat "$SETTINGS" | awk -F'=' '{
      key=""
      if ($1 ~ /^gtk-theme-name/) key="Theme Name:"
      else if ($1 ~ /^gtk-icon-theme-name/) key="Icon Set:"
      else if ($1 ~ /^gtk-font-name/) key="Font Name:"
      else if ($1 ~ /^gtk-cursor-theme-name/) key="Cursor Set:"
      else if ($1 ~ /^gtk-application-prefer-dark-theme/) key="Dark Mode:"
      else if ($1 ~ /^wallpaper/) key="Wallpaper:"

      if (key) {
        if (key == "Dark Mode:") {
          if ($2 == 0) {$2="false"} else {$2="true"}
        }
        printf "%-14s %s\n", key, $2
      }
    }'
}

set_wallpaper () {
  local IMAGE=$1

  if [ -z "$IMAGE" ]; then
    local WALLPAPERS="$(ls -1 "$WALLPAPERS_HOME" |
      awk '{ORS="'$AES'";} /.+\.(jpg|jpeg|png)/{print}')"

    pick_one "Select an image file:" "$WALLPAPERS" "vertical-6" || return 1
    [ -z "$REPLY" ] && return

    IMAGE="$WALLPAPERS_HOME/$(value "$REPLY")"
  fi
  
  if [[ ! "$IMAGE" =~ ^/ ]]; then
    echo "File path should be an absolute path"
    return 1
  elif [ ! -f "$IMAGE" ]; then
    echo "Invalid or unknown file path"
    return 1
  elif [[ ! "$IMAGE" =~ .+\.(jpg|jpeg|png)$ ]]; then
    echo "Only jpeg or png files are supported"
    return 1
  fi

  feh --no-fehbg --bg-fill "$IMAGE" &&
    sed -i "s;^wallpaper=.*;wallpaper=$IMAGE;" "$SETTINGS" &&
    echo "Wallpaper set to $IMAGE" ||
    echo "Failed to set the wallpaper"
}

load_wallpaper () {
  local IMAGE="$(cat "$SETTINGS" | awk -F'=' '/^wallpaper=/{print $2}')"

  set_wallpaper "$IMAGE" &&
    echo "Wallpaper has been loaded"

  if [ ! $? -eq 0 ]; then
    echo "Failed to load the wallpaper"
    return 1
  fi
}

help () {
  if [ "$1" = "once" ]; then
    echo "Usage: theme COMMAND [OBJECT] [ARGUMENTS]..."

    echo -e "\nCOMMANDS"
    printf " %-16s %s\n" \
      "help" "Show this help message." \
      "" "" \
      "load wallpaper" "Load the desktop wallpaper."

    return
  fi

  echo "Usage: COMMAND [OBJECT] [ARGUMENTS]..."

  echo -e "\nCOMMANDS"
  printf " %-25s %s\n" \
    "help" "Show this help message." \
    "" "" \
    "show status" "Show information and status related to theme." \
    "set wallpaper [<image>]" "Set the desktop wallpaper to the given image file."
}

loop () {
  clear

  while true; do
    prompt && history -s "$REPLY"

    set -f
    set_separator "line"
    local CMD=($(xargs -n1 <<< "$REPLY"))
    restore_separator && set +f

    if [ "${CMD[0]}" = "help" ]; then
      help
      continue
    elif [ "${CMD[0]}" = "clear" ]; then
      clear
      continue
    elif [ "${CMD[0]}" = "quit" ]; then
      break
    elif [ -z "${CMD[0]}" ]; then
      continue
    fi

    case "${CMD[0]}" in
      "show")
        case "${CMD[1]}" in
          "status") show_status;;
          *) echo "Unknown or invalid command";;
        esac;;
      "set")
        case "${CMD[1]}" in
          "wallpaper") set_wallpaper "${CMD[2]}";;
          *) echo "Unknown or invalid command";;
        esac;;
      *) echo "Unknown or invalid command";; 
    esac
  done

  clear
}

once () {
  case "$1" in
    "help") help once;;
    "load")
      case "$2" in
        "wallpaper") load_wallpaper || abort;;
        *) abort "Invalid or unknown command";;
      esac;;
    *) abort "Invalid or unknown command";;
  esac
}

if [ $# = 0 ]; then
  loop
else
  once "$@"
fi