#! /bin/sh

# Set the window size of the file chooser small to fit the screen
size=$(gsettings get org.gtk.Settings.FileChooser window-size)

if [[ $size != "(800, 600)" ]]; then
  gsettings set org.gtk.Settings.FileChooser window-size '(800, 600)'
fi

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
