#!/bin/bash

set -o pipefail

source /opt/stack/utils
source /opt/stack/displays/helpers

SETTINGS_FILE="${CONFIG_HOME}/desktop.json"

# Returns the list of any wallpapers found under
# the wallpapers home.
# Outputs:
#  A json array of image objects.
find_wallpapers () {
  if [[ ! -d  "${WALLPAPERS_HOME}" ]]; then
    echo '[]'
    return 0
  fi

  local wallpaper=''
  wallpaper+='"\"name\": \""$1"\","'
  wallpaper+='"\"type\": \""$2"\","'
  wallpaper+='"\"resolution\": \""$3"\","'
  wallpaper+='"\"bit\": \""$5"\","'
  wallpaper+='"\"color\": \""$6"\","'
  wallpaper+='"\"size\": \""$7"\""'
  wallpaper="\"{\"${wallpaper}\"},\""

  local wallpapers=''
  wallpapers="$(identify -quiet "${WALLPAPERS_HOME}/*" 2> /dev/null |
    awk '{
      if ($1 ~ /.(jpg|jpeg|png)$/) {
        n=split($1,a,"/")
        $1=a[n]
        print '"${wallpaper}"'
      }
    }'
  )"
  
  # Remove the extra comma after the last array element
  if [[ -n "${wallpapers}" ]]; then
    wallpapers="${wallpapers::-1}"
  fi

  echo "[${wallpapers}]"
}

# Shows a menu asking the user to select one wallpaper.
# Outputs:
#  A menu of wallpaper filenames.
pick_wallpaper () {
  local query='{key: .name, value: "\(.name) [\(.resolution)]"}'
  query="[.[]|${query}]"

  local wallpapers=''
  wallpapers="$(find_wallpapers | jq -cer "${query}")"

  if [[ $? -ne 0 ]]; then
    echo 'Unable to find wallpaper files'
    return 2
  fi

  local len=0
  len="$(count "${wallpapers}")" || return 1

  if [[ ${len} -eq 0 ]]; then
    echo 'No wallpaper files found'
    return 2
  fi

  pick_one 'Select wallpaper file:' "${wallpapers}" vertical || return $?
}


# Shows a menu asking the user to select one wallpaper
# alignment mode.
# Outputs:
#  A menu of wallpaper filenames.
pick_alignment_mode () {
  local modes=''
  modes+='{"key": "center", "value": "Center"},'
  modes+='{"key": "fill", "value": "Fill"},'
  modes+='{"key": "max", "value": "Max"},'
  modes+='{"key": "scale", "value": "Scale"},'
  modes+='{"key": "tile", "value": "Tile"}'
  modes="[${modes}]"

  pick_one 'Select alignment mode:' "${modes}" vertical || return $?
}

# Returns the list of pointing devices currently
# connected to the system.
# Outputs:
#  A json array of pointing device objects.
find_pointers () {
  local pointers=''
  pointers="$(xinput --list | awk '{
    if ($0 ~ "Virtual core pointer") {
      next
    } else if ($0 ~ "Virtual core keyboard") {
      exit
    }

    match($0, ".*↳ (.*)id=([0-9]+).*", a)
    gsub(/^[ \t]+/,"",a[1])
    gsub(/[ \t]+$/,"",a[1])
    gsub(/^[ \t]+/,"",a[2])
    gsub(/[ \t]+$/,"",a[2])

    schema="\"id\": \"%s\","
    schema=schema"\"name\": \"%s\""
    schema="{"schema"},"

    printf schema, a[2], a[1]
  }')" || return 1

  # Remove the extra comma after the last element
  if [[ -n "${pointers}" ]]; then
    pointers="${pointers::-1}"
  fi

  echo "[${pointers}]"
}

# Returns the pointing device with the given name.
# Arguments:
#  name: the name of the pointing device
# Outputs:
#  A json object of pointing device.
find_pointer () {
  local name="${1}"

  local id=''
  id="$(find_pointers |
    jq -cer ".[]|select(.name == \"${name}\")|.id")" || return 1

  local pointer=''
  pointer+="\"id\":\"${id}\","
  pointer+="\"name\":\"${name}\","

  pointer+="$(xinput --list-props "${id}" | awk '{
    match($0, "(.*)\\([0-9]{3}\\):(.*)", a)
    gsub(/^[ \t]+/,"",a[1])
    gsub(/[ \t]+$/,"",a[1])
    gsub(/^[ \t]+/,"",a[2])
    gsub(/[ \t]+$/,"",a[2])
    key=a[1];value=a[2]

    if (key == "Device Node") {
      key="node"
      gsub(/"/,"",value)
    } else if (key == "Device Enabled") {
      key="enabled"
    } else if (key == "libinput Accel Speed") {
      key="accel_speed"
    } else if (key == "libinput Accel Profile Enabled") {
      key="accel"
    } else if (key == "Device Accel Constant Deceleration") {
      key="const_decel"
    } else if (key == "Device Accel Adaptive Deceleration") {
      key="adapt_decel"
    } else if (key == "Device Accel Velocity Scaling") {
      key="velocity"
    } else {
      next
    }

    print "\""key"\":\""value"\","
  }')" || return 1

  # Remove the extra comma after the last element
  if [[ -n "${pointer}" ]]; then
    pointer="${pointer::-1}"
  fi

  echo "{${pointer}}"
}

# Shows a menu asking the user to select one pointing device.
# Outputs:
#  A menu of pointing devices.
pick_pointer () {
  local pointers=''
  pointers="$(find_pointers)"

  if [[ $? -ne 0 ]]; then
    echo 'Unable to find pointers'
    return 2
  fi

  local len=0
  len="$(count "${pointers}")" || return 1

  if [[ ${len} -eq 0 ]]; then
    echo 'No pointers found'
    return 2
  fi

  local query='[.[]|{key: .name, value: "\(.name)"}]'
  pointers="$(echo "${pointers}" | jq -cer "${query}")" || return 1

  pick_one 'Select pointer name:' "${pointers}" vertical || return $?
}

# Returns the list of stylus-pen devices currently
# connected to the system.
# Outputs:
#  A json array of stylus-pen device objects.
find_tablets () {
  local tablets=''
  tablets="$(xsetwacom --list devices | awk '{
    match($0, "(.*)id:(.*)type:(.*)", a)
    gsub(/^[ \t]+/,"",a[1])
    gsub(/[ \t]+$/,"",a[1])
    gsub(/^[ \t]+/,"",a[2])
    gsub(/[ \t]+$/,"",a[2])
    gsub(/^[ \t]+/,"",a[3])
    gsub(/[ \t]+$/,"",a[3])

    schema="\"id\": \"%s\","
    schema=schema"\"name\": \"%s\","
    schema=schema"\"type\": \"%s\","
    schema=schema"\"vendor\": \"wacom\""
    schema="{"schema"},"

    printf schema, a[2], a[1], a[3]
  }')" || return 1

  # Remove the extra comma after the last element
  if [[ -n "${tablets}" ]]; then
    tablets="${tablets::-1}"
  fi

  echo "[${tablets}]"
}

# Returns the tablet device with the given name.
# Arguments:
#  name: the name of the tablet device
# Outputs:
#  A json object of tablet device.
find_tablet () {
  local name="${1}"

  local query=".[]|select(.name == \"${name}\")"

  local tablet=''
  tablet="$(find_tablets | jq -cer "${query}")" || return 1

  local vendor=''
  vendor="$(get "${tablet}" '.vendor')" || return 1

  # Merge properties specific to wacom devices
  if [[ "${vendor}" == "wacom" ]]; then
    local props=''
    props="$(xsetwacom --get "${name}" all 2>&1 | awk '/^Option/{
      match($0, "Option \"(.*)\" \"(.*)\"", a)
      print "\""a[1]"\": \""a[2]"\","
    }')" || return 1

    # Remove the extra comma after the last key/value pair
    if [[ -n "${props}" ]]; then
      props="${props::-1}"
    fi

    tablet="$(echo "${tablet}" | jq -cer --argjson p "{${props}}" '. + $p')" || return 1
  fi

  echo "${tablet}"
}

# Checks if the given name corresponds to an
# existing tablet device.
# Arguments:
#  name: the name of a tablet device
# Returns:
#  0 if it is a tablet otherwise 1.
is_tablet () {
  local name="${1}"

  local query=".[]|select(.name == \"${name}\")"

  local tablet=''
  tablet="$(find_tablets | jq -cer "${query}")" || return 1

  if [[ -n "${tablet}" ]]; then
    return 0
  else
    return 1
  fi
}

# Checks if the tablet device with the given name
# has a scalable and mappable area.
# Arguments:
#  name: the name of a tablet device
# Returns:
#  0 if it is scalable otherwise 1.
is_scalable () {
  local name="${1}"

  local area=''
  area="$(find_tablet "${name}" | jq -cer '.Area')" || return 1

  if [[ -n "${area}" ]]; then
    return 0
  else
    return 1
  fi
}

# Shows a menu asking the user to select one tablet device.
# Outputs:
#  A menu of tablet devices.
pick_tablet () {
  local tablets=''
  tablets="$(find_tablets)"

  if [[ $? -ne 0 ]]; then
    echo 'Unable to find tablets'
    return 2
  fi

  local len=0
  len="$(count "${tablets}")" || return 1

  if [[ ${len} -eq 0 ]]; then
    echo 'No tablets have found'
    return 2
  fi

  local query='[.[]|{key: .name, value: .name}]'
  tablets="$(echo "${tablets}" | jq -cer "${query}")" || return 1

  pick_one 'Select tablet name:' "${tablets}" vertical || return $?
}

# Saves the wallpaper with the given file name
# into the settings file.
# Arguments:
#  name: the file name of the wallpaper
#  mode: center, fill, max, scale or tile
save_wallpaper_to_settings () {
  local name="${1}"
  local mode="${2}"

  local settings='{}'
  local wallpaper="{\"name\": \"${name}\", \"mode\": \"${mode}\"}"

  if [[ -f "${SETTINGS_FILE}" ]]; then
    settings="$(jq -e ".wallpaper = ${wallpaper} " "${SETTINGS_FILE}")" || return 1
  else
    settings="$(echo "{\"wallpaper\": ${wallpaper}}" | jq -e '.')" || return 1
  fi

  mkdir -p "${CONFIG_HOME}"
  echo "${settings}" > "${SETTINGS_FILE}"
}

# Saves the pointer speed factor into the settings file.
# Arguments:
#  factor: a speed factor between [0,1]
save_pointer_speed_to_settings () {
  local factor="${1}"

  local settings='{}'
  local pointer="{\"speed\": ${factor}}"

  if [[ -f "${SETTINGS_FILE}" ]]; then
    settings="$(jq -e ".pointer = ${pointer} " "${SETTINGS_FILE}")" || return 1
  else
    settings="$(echo "{\"pointer\": ${pointer}}" | jq -e '.')" || return 1
  fi

  mkdir -p "${CONFIG_HOME}"
  echo "${settings}" > "${SETTINGS_FILE}"
}

# Saves the scale factor of the tablet with the given
# name into the settings file.
# Arguments:
#  name:  the name of a tablet device
#  scale: the scale factor [0.1,1]
save_tablet_scale_to_settings () {
  local name="${1}"
  local scale="${2}"
  
  local settings='{}'
  local tablet="{\"name\": \"${name}\", \"scale\": ${scale}}"

  if [[ -f "${SETTINGS_FILE}" ]]; then
    local tablets=''
    tablets="$(jq '.tablets|if . then . else empty end' "${SETTINGS_FILE}")"

    if [[ -n "${tablets}" ]]; then
      local query=''
      query=".tablets[]|select(.name == \"${name}\")"

      local exists=''
      exists="$(jq "${query}" "${SETTINGS_FILE}")"

      if [[ -n "${exists}" ]]; then
        query="(${query}|.scale)|= ${scale}"
      else
        query=".tablets += [${tablet}]"
      fi

      settings="$(jq -e "${query}" "${SETTINGS_FILE}")" || return 1
    else
      settings="$(jq -e ".tablets = [${tablet}] " "${SETTINGS_FILE}")" || return 1
    fi
  else
    settings="$(echo "{\"tablets\": [${tablet}]}" | jq -e '.')" || return 1
  fi

  mkdir -p "${CONFIG_HOME}"
  echo "${settings}" > "${SETTINGS_FILE}"
}

# Shows a menu asking user to select a mapping target which
# could be any active display output or the special desktop
# value.
# Outputs:
#  A menu of display namesi and desktop.
pick_mapping_target () {
  # Convert outputs list into an array of {key, value} options
  local key='\(.device_name)'
  local value='\(.device_name):[\(if .model_name then .model_name else "NA" end)]'

  local query="[.[]|{key: \"${key}\", value: \"${value}\"}]"

  local options=''
  options="$(find_outputs active | jq -cer "${query}")" || return 1

  # Append the special desktop option value into options
  local desktop='[{"key": "desktop", "value": "Desktop:[ALL]"}]'

  options="$(echo "${options}" | jq -cer --argjson d "${desktop}" '. + $d')" || return 1
  
  pick_one "Select mapping target:" "${options}" vertical || return $?
}

