#!/bin/bash

set -o pipefail

source /opt/stack/utils
source /opt/stack/desktop/commands

# Shows the help message.
# Arguments:
#  mode: loop or once
# Outputs:
#  A long help message.
show_help () {
  local mode="${1:-"once"}"

  if [[ "${mode}" == "once" ]]; then
    echo 'Usage: desktop [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
    
    echo -e '\nOPTIONS'
    printf ' %-8s %s\n' \
      '-h' 'Show this help message.' \
      '-q' 'Do not play beep sounds.' \
      '-s' 'Run on script mode.'
  
    echo -e '\nCOMMANDS'
  else
    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'

    echo -e '\nCOMMANDS'
    printf ' %-35s %s\n' \
      'help' 'Show this help message.' \
      '' ''
  fi

  printf ' %-35s %s\n' \
    'show status' 'Show the status of the desktop environment.' \
    'show pointer <name>' 'Show a pointing device.' \
    'show tablet <name>' 'Show a tablet device.' \
    '' '' \
    'list wallpapers' 'List the available wallapers.' \
    'list pointers' 'List the available pointing devices.' \
    'list tablets' 'List the connected tablets.' \
    '' '' \
    'set wallpaper <name> <mode>' 'Set the desktop wallpaper on center,' \
    '' 'fill, scale, max or tile mode.' \
    'init wallpaper' 'Initialize the desktop wallpaper.' \
    '' '' \
    'speed pointer <factor>' 'Set the pointer speed to a factor between' \
    '' '[0, 1] where 0 means slow and 1 fast.' \
    'init pointer' 'Initialize the pointer.' \
    '' '' \
    'scale tablet <name> <factor>' 'Scale down the tablet area in range [0.1-1],' \
    '' 'where factor 1 means remove scaling.' \
    'map tablet <name> <display>' 'Map a tablet to a screen display' \
    '' 'or just use desktop to reset mapping.' \
    'init tablets' 'Initialize any connected tablets.'
}

run () {
  local opt=''

  while getopts ':hqs' opt; do
    case "${opt}" in
     'h')
        show_help once
        return 0;;
     'q') QUIET='true';;
     's') ON_SCRIPT_MODE='true';;
     *)
      echo "Ooops, invalid or unknown option -${OPTARG}!"
      $(exit 2) || beep
      return $?;;
    esac
  done

  shift $((OPTIND-1))

  local mode='once'
  if [[ $# -eq 0 ]]; then
    mode='loop'
    clear
  fi

  while true; do
    if [[ "${mode}" == "loop" ]]; then
      prompt desktop
    else
      REPLY="$@"
    fi

    set -f
    set_separator line
    local args=($(xargs -n1 <<< "${REPLY}"))
    restore_separator && set +f
    REPLY=''

    local cmd="${args[0]}"
    local obj="${args[1]}"

    if [[ "${mode}" == "loop" ]]; then
      case "${cmd}${obj:+ ${obj}}" in
        'help') clear && show_help loop && continue;;
        'clear') clear && continue;;
        'quit') break;;
        '') continue;;
      esac
    fi

    case "${cmd}${obj:+ ${obj}}" in
      'show status') show_status;;
      'show pointer') show_pointer "${args[2]}";;
      'show tablet') show_tablet "${args[2]}";;
      'set wallpaper') set_wallpaper "${args[2]}" "${args[3]}" && beep;;
      'speed pointer') set_pointer_speed "${args[2]}" && beep;;
      'scale tablet') scale_tablet "${args[2]}" "${args[3]}" && beep;;
      'map tablet') map_tablet "${args[2]}" "${args[3]}" && beep;;
      'list wallpapers') list_wallpapers;;
      'list pointers') list_pointers;;
      'list tablets') list_tablets;;
      'init pointer') init_pointer && beep;;
      'init tablets') init_tablets && beep;;
      'init wallpaper') init_wallpaper && beep;;
      *)
        echo 'Ooops, invalid or unknown command!'
        $(return 2);;
    esac || beep

    local exit_code=$?
    if [[ "${mode}" == "once" ]]; then
      return ${exit_code}
    fi
  done

  clear
}

run "$@"

