#!/bin/bash

set -Eeo pipefail

# Reads for hooked in usb removable flash
# drives and prints them out one by one.
run () {
  local fields='name,type,size,rm,tran,vendor,model'

  local criteria=''
  criteria+='.type == "disk" and '
  criteria+='.rm == true and '
  criteria+='.tran == "usb"'

  local facade=''
  facade+='\(.vendor|gsub("^\\s+|\\s+$";"")|.[:15])'
  facade+=':\(.size|gsub("\\.[0-9]*";""))'
  
  local query="[.blockdevices[]|select(${criteria})|\"${facade}\"]"
  query+='|join("%{F#444444} | %{F-}")'

  lsblk -J -o "${fields}" | jq -cr "${query}"
}

run "$@"

