#!/bin/bash

set -Eeo pipefail

source /opt/stack/commons/error.sh
source /opt/stack/commons/math.sh
source /opt/stack/tools/notifications/helpers.sh

# Reads the state of notifications and prints
# out the total number of pending ones.
run () {
  local state=''
  state="$(get_notifications_state)"

  if has_failed; then
    echo 'Err!'
    return 0
  fi

  local is_paused='false'
  is_paused="$(echo "${state}" | jq -cr '.is_paused')"

  local icon=''
  if is_true "${is_paused}"; then
    icon=''
  fi

  local pending=''
  pending="$(echo "${state}" | jq -cr '.pending + .displayed' | xargs printf '%02d')"
    
  echo "${icon} ${pending}"
}

run "$@"

