#!/bin/bash

set -o pipefail

source /opt/stack/utils
source /opt/stack/notifications/commands

# Shows the help message.
# Arguments:
#  mode: loop or once
# Outputs:
#  A long help message.
show_help () {
  local mode="${1:-"once"}"

  if equals "${mode}" 'once'; then
    echo 'Usage: notifications [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
    
    echo -e '\nOPTIONS'
    printf ' %-8s %s\n' \
      '-h' 'Show this help message.' \
      '-q' 'Do not play beep sounds.' \
      '-s' 'Run on script mode.'

    echo -e '\nCOMMANDS'
  else
    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'

    echo -e '\nCOMMANDS'
    printf ' %-28s %s\n' \
      'help' 'Show this help message.' \
      '' ''
  fi

  printf ' %-28s %s\n' \
    'show status' 'Show the status of notifications.' \
    'get state' 'Return the state of the notifications stream.' \
    '' '' \
    'list all id|appname' 'List all notifications by id (default) or appname.' \
    '' '' \
    'set popup on|off' 'Show or hide popup notifications.' \
    'set volume <percent>' 'Set the volume of the notifications sound.' \
    '' '' \
    'mute all' 'Pause the notifications stream.' \
    'unmute all' 'Restore the notifications stream.' \
    'clean all' 'Remove all notifications.' \
    '' '' \
    'start' 'Start the notifications service.' \
    'restart' 'Restart the notifications service.'
}

run () {
  local opt=''

  while getopts ':hqs' opt; do
    case "${opt}" in
     'h')
        show_help once
        return 0;;
     'q') QUIET='true';;
     's') ON_SCRIPT_MODE='true';;
     *)
      echo "Ooops, invalid or unknown option -${OPTARG}!"
      $(exit 2) || beep
      return $?;;
    esac
  done

  shift $((OPTIND-1))

  local mode='once'
  if is_true "$# = 0"; then
    mode='loop'
    clear
  fi

  while true; do
    if equals "${mode}" 'loop'; then
      prompt notifications
    else
      REPLY="$@"
    fi

    set -f
    set_separator line
    local args=($(xargs -n1 <<< "${REPLY}"))
    restore_separator && set +f
    REPLY=''

    local cmd="${args[0]}"
    local obj="${args[1]}"

    if equals "${mode}" 'loop'; then
      case "${cmd}${obj:+ ${obj}}" in
        'help') clear && show_help loop && continue;;
        'clear') clear && continue;;
        'quit') break;;
        '') continue;;
      esac
    fi

    case "${cmd}${obj:+ ${obj}}" in
      'show status') show_status;;
      'list all') list_all "${args[2]}" "${args[3]}";;
      'mute all') mute_all && beep;;
      'unmute all') unmute_all && beep;;
      'clean all') clean_all && beep;;
      'set popup') set_popup "${args[2]}" && beep;;
      'set volume') set_volume "${args[2]}" && beep;;
      'start') start && beep;;
      'restart') restart && beep;;
      'get state') get_state;;
      *)
        echo 'Ooops, invalid or unknown command!'
        $(return 2);;
    esac || beep

    local exit_code=$?
    if equals "${mode}" 'once'; then
      return ${exit_code}
    fi
  done

  clear
}

run "$@"


