#!/bin/bash

set -o pipefail

source /opt/stack/utils

# Resizes the windows according to the given direction
# and delta factors.
# Arguments:
#  side:  left, right, up, down
#  delta: an integer number
run () {
  local side="${1}"
  local delta="${2:-"10"}"

  local orientation=''

  case "${side}" in
    'right')
      orientation='horizontal'
      delta=$(calc "1 * ${delta}");;
    'left')
      orientation='horizontal'
      delta=$(calc "-1 * ${delta}");;
    'up')
      orientation='vertical'
      delta=$(calc "-1 * ${delta}");;
    'down')
      orientation='vertical'
      delta=$(calc "1 * ${delta}");;
  esac

  local x=0
  local y=0
  local direction=''
  local opposite=''

  if equals "${orientation}" 'horizontal'; then
    x=${delta}
    direction='right'
    opposite='left'
  elif equals "${orientation}" 'vertical'; then
    y=${delta}
    direction='top'
    opposite='bottom'
  fi

  bspc node -z "${direction}" "${x}" "${y}" ||
    bspc node -z "${opposite}" "${x}" "${y}"
}

run "$@"

