#!/bin/bash

set -Eeo pipefail

# Swaps the windows in the currently focused desktop
# with those of the given desktop.
# Arguments:
#  target: the index of the target desktop
run () {
  local target="${1}"

  # Set any sticky window of the source and target to not sticky
  local nodes=''
  nodes="$(
    bspc query -N -n .sticky -d focused;
    bspc query -N -n .sticky -d "${target}"
  )"

  local node=''
  
  while read -r node; do
    bspc node "${node}" -g sticky
  done <<< "${nodes}"
  
  bspc desktop -s "${target}" --follow

  # Set windows back to sticky mode
  while read -r node; do
    bspc node "${node}" -g sticky
  done <<< "${nodes}"

  # Fix any desktop inconsistencies caused by the swap
  desktop -qs fix workspaces
}

run "$@"

