#!/bin/bash

set -o pipefail

source /opt/stack/utils

# Returns the list of all audio cards.
# Arguments:
#  none
# Outputs:
#  A json array of audio cards.
find_cards () {
  pactl --format=json list cards || return 1
}

# Returns the audio card identified by the given
# index number.
# Arguments:
#  index: a zero-based integer
# Outputs:
#  A json object of an audio card.
find_card () {
  local index="${1}"

  local query=".[]|select(.index|tostring == \"${index}\")"

  find_cards | jq -cer "${query}" || return 1
}

# Shows a menu asking the user to select an audio card,
# where the answer is kept in the global var REPLY.
# Arguments:
#  prompt: a prompt text line
# Outputs:
#  A menu of audio card names.
pick_card () {
  local prompt="${1}"

  local query='{key: .index, value: "\(.index):\(.properties|'
  query+='if ."device.nick" then ."device.nick" else ."device.alias" end)"}'
  query="[.[]|${query}]"

  local cards=''
  cards="$(find_cards | jq -cer "${query}")" || return 1

  local len=0
  len=$(count "${cards}") || return 1

  if [[ ${len} -eq 0 ]]; then
    echo 'No audio cards have found'
    return 2
  fi
  
  pick_one "${prompt}" "${cards}" vertical || return $?
}

# Shows a menu asking the user to select a profile of the
# given audio card, where the answer is kept in the global
# var REPLY.
# Arguments:
#  prompt: a prompt text line
#  card:   a json object of an audio card
# Outputs:
#  A menu of audio card profile names.
pick_profile () {
  local prompt="${1}"
  local card="${2}"

  local query='{key: .key, value: .key}'
  query="[.profiles|to_entries[]|${query}]"

  local profiles=''
  profiles="$(echo "${card}" | jq -cer "${query}")" || return 1

  local len=0
  len="$(count "${profiles}")" || return 1

  if [[ ${len} == 0 ]]; then
    echo 'No audio profiles found'
    return 2
  fi
  
  pick_one "${prompt}" "${profiles}" vertical || return $?
}

# Shows a menu asking the user to select an audio module
# with the given type, where the answer is kept in the
# global var REPLY.
# Arguments:
#  prompt: a prompt text line
#  type:   output or input
# Outputs:
#  A menu of audio output or input module names.
pick_module () {
  local prompt="${1}"
  local type="${2}"

  local query='{key: .index, value: "\(.name)'
  query+=' [\(.properties|if ."device.nick" then ."device.nick" else ."device.alias" end)]"}'
  query="[.[]|=.|map((.ports[] + {index, properties}))|.[]|${query}]"
  
  local object='sinks'
  if [[ "${type}" == "input" ]]; then
    object='sources'
  fi

  local modules=''
  modules="$(pactl --format=json list "${object}" | jq -cer "${query}")" || return 1

  local len=0
  len="$(count "${modules}")" || return 1

  if [[ ${len} == 0 ]]; then
    echo "No ${type} modules have found"
    return 2
  fi
  
  pick_one "${prompt}" "${modules}" vertical || return $?
}

