#!/bin/bash

set -o pipefail

source /opt/stack/utils

SETTINGS_FILE="${CONFIG_HOME}/security.json"

# Shows the current status of the system's security.
# Arguments:
#  None
# Outputs:
#  A verbose list of text data.
show_status () {
  passwd -S | awk '{
    status="protected"
    if ($2 == "L") {
      status="locked"
    } else if ($2 == "NP") {
      status="no password"
    }

    print "User:      "$1
    print "Status:    "status
    print "Changed:   "$3
  }' || return 1

  cat /etc/security/faillock.conf | awk '{
    if ($0 ~ /^deny =.*/) {
      print "Attempts:  "$3
    } else if ($0 ~ /^unlock_time =.*/) {
      print "Unblock:   "$3" secs"
    } else if ($0 ~ /^fail_interval =.*/) {
      print "Interval:  "$3" secs"
    }
  }' || return 1

  local locker_process=''
  locker_process="$(ps ax -o "command" | jc --ps |
    jq '.[]|select(.command|test("^xautolock"))|.command')" || return 1
  
  if [[ -n "${locker_process}" ]]; then
    echo "${locker_process}" | awk '{
      match($0,/.* -time (.*) -corners.*/,a)
      print "Locker:    "a[1]" mins"
    }'
  else
    echo "Locker:    off"
  fi
}

# Sets the interval time of the screen locker, where
# 0 means deactivate the locker.
# Arguments:
#  mins:    an integer interval in mins or 0
#  persist: save or nosave, default is save
set_screen_locker () {
  local mins="${1}"
  local persist="${2:-"save"}"

  if [[ -z "${mins}" ]]; then
    echo 'Missing the interval time'
    return 2
  elif [[ ! "${mins}" =~ ^[0-9]{,2}$ ]]; then
    echo 'Invalid interval time'
    return 2
  elif [[ ${mins} -lt 0 ]] || [[ ${mins} -gt 60 ]]; then
    echo 'Interval time out of range [0,60]'
    return 2
  fi

  # Exit possibly running locker instance
  xautolock -exit &> /dev/null
  sleep 1

  if [[ ${mins} -gt 0 ]]; then
    xautolock -locker 'security lock screen' -nowlocker 'security lock screen' -time "${mins}" -corners 0-00 -detectsleep &
    echo "Screen locker set to ${mins} mins"
  else
    echo 'Screen locker has been disabled'
  fi

  # Save locker interval into settings file
  if [[ "${persist}" == "save" ]]; then
    local settings='{}'
    local locker="{\"interval\": ${mins}}"

    if [[ -f "${SETTINGS_FILE}" ]]; then
      settings="$(jq -e ".locker = ${locker} " "${SETTINGS_FILE}")" || return 1
    else
      settings="$(echo "{\"locker\": ${locker}}" | jq -e '.')" || return 1
    fi

    mkdir -p "${CONFIG_HOME}"
    echo "${settings}" > "${SETTINGS_FILE}"
  fi
}

# Initializes the screen locker to interval being set
# in the settings file.
# Arguments:
#  None
init_screen_locker () {
  if [[ ! -f "${SETTINGS_FILE}" ]]; then
    echo 'No locker settings found'
    return 0
  fi

  local locker=''
  locker="$(jq '.locker|if . then . else empty end' "${SETTINGS_FILE}")"

  if [[ -z "${locker}" ]]; then
    echo 'No locker settings found'
    return 0
  fi

  local interval=''
  interval="$(get "${locker}" '.interval')" || return 1

  set_screen_locker "${interval}" "nosave"

  if [[ $? -ne 0 ]]; then
    echo 'Failed to set locker'
    return 2
  fi

  echo 'Locker has been set'
}

# Locks the screen making sure notifications stream is muted
# before lock and resets it back to it's previous state
# after user unlocks the screen.
# Arguments:
#  None
lock_screen () {
  local query=''
  query+='[.[]|select(.command|test("xsecurelock.*"))]'
  query+='|if length > 0 then "true" else "false" end'

  local is_locked=''
  is_locked="$(ps aux | grep -v 'jq' | jc --ps | jq -cr "${query}")" || return 1

  if [[ "${is_locked}" == "true" ]]; then
    echo 'Screen locker is already running'
    return 0
  fi

  local is_paused=''
  is_paused="$(notifications get state | jq -cr '.is_paused')"

  if [[ "${is_paused}" == "false" ]]; then
    notifications mute all
  fi

  env XSECURELOCK_FONT='PixelMix' \
    XSECURELOCK_SAVER="saver_clock" \
    XSECURELOCK_NO_COMPOSITE=1 \
    XSECURELOCK_BLANK_TIMEOUT=-1 \
    xsecurelock >/dev/null 2>&1

  if [[ $? -ne 0 ]]; then
    echo 'Unable to lock the screen'
    return 2
  fi

  # Reset notifications stream to previous state
  if [[ "${is_paused}" == "false" ]]; then
    notifications unmute all
  fi
}

# Change the password of the current user.
# Arguments:
#  None
set_user_password () {
  ask_secret 'Enter current password:'
  local password="${REPLY}"

  if ! authenticate_user "${password}"; then
    echo 'Sorry incorrect password'
    return 2
  fi

  ask_secret 'Enter new password:'
  local new_password="${REPLY}"

  if ! confirm_secret "Retype new password:" "${new_password}"; then
    echo 'New password does not match'
    return 2
  fi

  echo -e "${password}\n${new_password}\n${new_password}" |
    passwd --quiet >/dev/null 2>&1

  if [[ $? -ne 0 ]]; then
    echo 'Unable to set user password'
    return 2
  fi

  echo 'User password has been set'
}

# Logs the user out, terminating the current xorg session.
# Arguments:
#  None
logout_user () {
  bspc quit

  if [[ $? -ne 0 ]]; then
    echo 'Unable to log the user out'
    return 2
  fi
}

# Sets the max number of failed attempts before
# the user's password gets blocked.
# Arguments:
#  attempts: the max number of failed password attempts
set_faillock_attempts () {
  local attempts="${1}"

  if [[ -z "${attempts}" ]]; then
    echo 'Missing the attempts value'
    return 2
  elif [[ ! "${attempts}" =~ ^[1-9][0-9]*$ ]]; then
    echo 'Invalid attempts value'
    return 2
  elif [[ ! ${attempts} -gt 0 ]]; then
    echo 'Attempts should be greater than 0'
    return 2
  fi

  sudo sed -ri "s;deny =.*;deny = ${attempts};" /etc/security/faillock.conf

  if [[ $? -ne 0 ]]; then
    echo 'Unable to set faillock attempts'
    return 2
  fi

  echo "Failock attempts set to ${attempts}"
}

# Sets the time after which a blocked password
# should get unblocked.
# Arguments:
#  time: the secs to wait a password to be unblocked
set_faillock_unblock () {
  local time="${1}"

  if [[ -z "${time}" ]]; then
    echo 'Missing the unblock time value'
    return 2
  elif [[ ! "${time}" =~ ^[1-9][0-9]*$ ]]; then
    echo 'Invalid unblock time value'
    return 2
  elif [[ ! ${time} -gt 0 ]]; then
    echo 'Unblock time should be greater than 0'
    return 2
  fi

  sudo sed -ri "s;unlock_time =.*;unlock_time = ${time};" /etc/security/faillock.conf

  if [[ $? -ne 0 ]]; then
    echo 'Unable to set faillock unblock time'
    return 2
  fi

  echo "Failock unblock time set to ${time} secs"
}

# Sets the interval in which a failed password attempt
# should be counted as consecutive attempt to trigger
# a password block.
# Arguments:
#  time: the secs between consecutive failed attempts
set_faillock_interval () {
  local time="${1}"

  if [[ -z "${time}" ]]; then
    echo 'Missing the interval value'
    return 2
  elif [[ ! "${time}" =~ ^[1-9][0-9]*$ ]]; then
    echo 'Invalid interval value'
    return 2
  elif [[ ! ${time} -gt 0 ]]; then
    echo 'Interval should be greater than 0'
    return 2
  fi

  sudo sed -ri "s;fail_interval =.*;fail_interval = ${time};" /etc/security/faillock.conf

  if [[ $? -ne 0 ]]; then
    echo 'Unable to set faillock interval'
    return 2
  fi

  echo "Failock interval set to ${time} secs"
}

