#!/bin/bash

set -o pipefail

source /opt/stack/utils
source /opt/stack/security/commands

# Shows the help message.
# Arguments:
#  mode: loop or once
# Outputs:
#  A long help message.
show_help () {
  local mode="${1}"

  if equals "${mode}" 'once'; then
    echo 'Usage: security [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
    
    echo -e '\nOPTIONS'
    printf ' %-8s %s\n' \
      '-h' 'Show this help message.' \
      '-q' 'Do not play beep sounds.' \
      '-s' 'Run on script mode.'
  
    echo -e '\nCOMMANDS'
  else
    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'

    echo -e '\nCOMMANDS'
    printf ' %-24s %s\n' \
      'help' 'Show this help message.' \
      '' ''
  fi

  printf ' %-24s %s\n' \
    'show status' 'Show the status of the system security.' \
    '' '' \
    'set password' 'Set a new user password.' \
    'set attempts <max>' 'Set max fails before password is blocked.' \
    'set unblock <time>' 'Set the time in secs a password is unblocked.' \
    'set interval <time>' 'Set the interval in secs between consecutive password fails.' \
    '' '' \
    'set locker <interval>' 'Set the screen locker interval time in mins,' \
    '' 'where 0 means deactivate the locker.' \
    'init locker' 'Initialize the screen locker from settings.' \
    '' '' \
    'lock screen' 'Lock the screen.' \
    'logout user' 'Logout the user.'
}

run () {
  local opt=''

  while getopts ':hqs' opt; do
    case "${opt}" in
     'h')
        set_quiet_mode 'on'
        show_help once
        return 0;;
     'q') set_quiet_mode 'on';;
     's') set_script_mode 'on';;
     *)
      echo "Ooops, invalid or unknown option -${OPTARG}!"
      beep 2
      return $?;;
    esac
  done

  shift $((OPTIND-1))

  local mode='once'
  if is_true "$# = 0"; then
    mode='loop'
    clear
  fi

  while true; do
    if equals "${mode}" 'loop'; then
      prompt security
    else
      REPLY="$@"
    fi

    set -f
    set_separator line
    local args=($(xargs -n1 <<< "${REPLY}"))
    restore_separator && set +f
    REPLY=''

    local cmd="${args[0]}"
    local obj="${args[1]}"

    if equals "${mode}" 'loop'; then
      case "${cmd}${obj:+ ${obj}}" in
        'help') clear && show_help && continue;;
        'clear') clear && continue;;
        'quit') break;;
        '') continue;;
      esac
    fi

    case "${cmd}${obj:+ ${obj}}" in
      'show status') show_status;;
      'set locker') set_screen_locker "${args[2]}";;
      'set password') set_user_password;;
      'set attempts') set_faillock_attempts "${args[2]}";;
      'set unblock') set_faillock_unblock "${args[2]}";;
      'set interval') set_faillock_interval "${args[2]}";;
      'init locker') init_screen_locker;;
      'lock screen') lock_screen;;
      'logout user') logout_user;;
      *)
        echo 'Ooops, invalid or unknown command!'
        $(return 2);;
    esac

    # Save exit status code of the last executed cmd
    local exit_code=$?
  
    if is_true "${exit_code} = 1"; then
      echo 'Ooops, an unknwon error occurred!'
    fi

    on_loud_mode && beep "${exit_code}"

    if equals "${mode}" 'once'; then
      return ${exit_code}
    fi
  done

  clear
}

run "$@"

