#!/bin/sh

SD=" Shutdown"
RB=" Reboot"
LO=" Logout"
LK=" Lock"

HIDE_PROMT="inputbar {children: [entry];}"
EXACT_LINES="listview {lines: 4;}"

CHOSEN=$(printf "$SD\n$RB\n$LO\n$LK" | rofi -dmenu -i -theme-str "${HIDE_PROMT} ${EXACT_LINES}")

case "$CHOSEN" in
	"$SD") shutdown now ;;
	"$RB") reboot ;;
	"$LO") bspc quit ;;
	"$LK") slock ;;
	*) exit 1 ;;
esac
