#!/bin/bash

run () {
  # Terminate already running bar instances
  polybar-msg cmd quit

  # Start new loggin section
  echo "---" | tee -a /tmp/polybar.log

  # Launch polybar for the primary monitor
  local primary=''
  primary="$(polybar -m | awk -F':' '/primary/{print $1}')"

  MONITOR="${primary}" polybar -r primary 2>&1 |
    tee -a /tmp/polybar.log & disown

  # Launch polybars for each secondary monitor
  local secondaries=''
  secondaries="$(polybar -m | awk -F':' '!/primary/{print $1}')"

  local monitor=''

  while read -r monitor; do
   MONITOR="${monitor}" polybar -r secondary 2>&1 |
      tee -a /tmp/polybar.log & disown
  done <<< "${secondaries}"

  echo 'Bars have been launched...'
}

run "$@"

