name: stak
base: core20
version: '0.1.0'
summary: A tool to automate the setup of a development stack
description: |
  Stak is an open source tool to speed up and automate the setup
  and installation process of your development stack on debian and
  gnome based linux distributions.
license: MIT
title: Stak
source-code: https://github.com/tzeikob/stak
website: https://github.com/tzeikob/stak
issues: https://github.com/tzeikob/stak/issues
contact: iakopap@gmail.com

grade: devel
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  stak:
    command: bin/script.sh

parts:
  stak:
    plugin: dump
    source: .
    organize:
      script.sh: bin/