#!/bin/bash

desktop -qs init workspaces
desktop -qs init wallpaper &
desktop -qs init scratchpad &
desktop -qs init bars &
desktop -qs init bindings &
desktop -qs init pointer &
desktop -qs init tablets &

bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc config normal_border_color "#AAAAAA"
bspc config active_border_color "#F0C674"
bspc config focused_border_color "#FF79C6"

bspc rule -a scratch sticky=off state=floating hidden=on
bspc config external_rules_command "${HOME}/.config/bspwm/rules"
